'use strict';
// 仅用于需求评审的本地界面和状态演示，没有业务服务或真实身份认证。
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=v=>JSON.parse(JSON.stringify(v));
const uid=()=>globalThis.crypto?.randomUUID?.()||'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const n=Math.floor(Math.random()*16);return(c==='x'?n:(n&3|8)).toString(16)});
const roles={enterprise:'企业',city:'市级审核',province:'省级业务',admin:'系统管理'};
const statuses={DRAFT:['草稿','gray'],PENDING:['待备案','amber'],RETURNED:['备案退回','red'],CITY_PENDING:['待市级审核','amber'],CITY_RETURNED:['市级退回','red'],PROVINCE_PENDING:['待省级审核','amber'],PROVINCE_RETURNED:['省级退回','red'],APPROVED:['已通过','green'],QUEUED:['待发送','gray'],SENDING:['发送中','amber'],ACKNOWLEDGED:['模拟接收成功','green'],REJECTED:['接收拒绝','red'],UNKNOWN:['结果未知','amber'],DELETED:['已逻辑删除','red']};
const badge=(s)=>`<span class="tag ${statuses[s]?.[1]||'gray'}">${esc(statuses[s]?.[0]||s)}</span>`;
const rt=['关闭破产','停业整顿','经济性裁员','业务转移','自然减员','正常解除或终止劳动合同','国际因素变化影响','自然灾害','重大事件影响','其他'].map((name,i)=>({code:'RT'+String(i+1).padStart(2,'0'),name}));
const rc=['产业结构调整','重大技术改革','节能减排、淘汰落后产能','订单不足','原材料涨价','工资、社保等用工成本上升','自然减员','经营资金困难','税收政策变化（包括税负增加或出口退税减少等）','季节性用工','其他','自行离职','工作调动、企业内部调剂','劳动关系转移、劳务派遣'].map((name,i)=>({code:'RC'+String(i+1).padStart(2,'0'),name}));
const nature={N1:['国有',[['N101','国有独资'],['N102','国有控股']]],N2:['集体',[['N201','城镇集体'],['N202','农村集体']]],N3:['民营',[['N301','私营企业'],['N302','个体经营']]],N4:['外资',[['N401','外商投资'],['N402','港澳台投资']]],N9:['其他',[['N901','其他性质']]]};
const industry={I1:['农林牧渔',[['I101','种植养殖'],['I102','其他农林牧渔']]],I2:['工业',[['I201','制造业'],['I202','采矿及能源']]],I3:['建筑',[['I301','房屋建筑'],['I302','其他建筑']]],I4:['服务',[['I401','商贸服务'],['I402','其他服务']]],I9:['其他',[['I901','其他行业']]]};
const nameOf=(dict,code)=>Object.values(dict).flatMap(v=>v[1]).find(v=>v[0]===code)?.[1]||code;
const codeName=(list,code)=>list.find(v=>v.code===code)?.name||'—';
const menus={
 enterprise:['guide','dashboard','profile','report','history','notices'],
 city:['guide','dashboard','review','history','notices'],
 province:['guide','dashboard','filing','archives','review','query','stats','compare','trend','correction','supplement','exchange','notices','trash','users','roles','periods','dict','monitor','audit'],
 admin:['guide','dashboard','users','roles','periods','dict','monitor','audit']
};
const meta={
 guide:['项目导览','先理解目标，再沿一条完整业务链体验界面。','FR-01至28'],
 dashboard:['工作台','查看当前角色的任务，直接进入下一项操作。','FR-01、03、07、10、13'],
 profile:['企业资料与备案','维护自身资料；备案通过后才能填报，变更通过前继续使用旧档案。','FR-02、03'],
 filing:['备案审批','查看完整资料及变更差异，单条通过或填写理由退回。','FR-03'],
 report:['当期填报','填报2026年9月企业就业人数；减少时补充类型与原因。','FR-04、05、11'],
 review:['月报审核','核对该提交版本的企业资料、人数、原因和审核记录。','FR-07、08、10、11'],
 history:['历史报表','读取历次提交、退回理由及修订记录，已提交快照不可覆盖。','FR-06、07'],
 archives:['已备案企业','当前档案和调查期快照分别查询；详情只读。','FR-09'],
 query:['综合查询与导出','按交集筛选报表，导出包含全部命中数据。','FR-14、15'],
 stats:['月度统计','只统计省级已通过且未删除的报表，明确原始与修订口径。','FR-13、16'],
 compare:['两期对比','共同样本为默认；新增、缺失企业不按零人数处理。','FR-17'],
 trend:['连续期趋势','按月观察变化比例，缺月断线，季度不累加就业人数。','FR-18'],
 correction:['独立数据修订','另存修订，显式生效后影响修订口径，保留原始数据。','FR-12、13'],
 supplement:['补报授权','仅解锁指定企业及月份的草稿或退回记录，默认72小时。','FR-11、21'],
 exchange:['国家报送','冻结数据和口径；根据接收回执判断结果。','FR-26、IF-01'],
 notices:['通知公告','阅读省级通知；省级业务仅维护自己发布的通知。','FR-19、20'],
 users:['用户管理','管理账号、归属及启停；已有提交记录的用户不可删除。','FR-22'],
 roles:['角色与权限','业务身份互斥，管理权限显式授予，撤权立即生效。','FR-01、23'],
 periods:['调查期设置','默认本月1日至11日采集上月数据；截止时刻不包含。','FR-21'],
 dict:['字典、地区与编码','维护两级分类和地区；已引用代码只停用，保留历史。','FR-28'],
 monitor:['运行监控','查看节点与队列状态；采集失败显示不可用。','FR-24、IF-04'],
 audit:['审计与版本','查看人、时间、对象、操作及理由，原始记录保留。','FR-27'],
 trash:['历史删除与恢复','先预览影响，再二次确认；冻结批次保留，30日内可恢复。','FR-25'],
 login:['登录体验','演示登录、错误提示、初次改密及会话失效的界面方向。','FR-01、NFR-06、07']
};
const reviewRules={
 profile:['企业编码可录入及申请变更，地区只读；必填提交校验，格式错误不能保存。','资料通过后只读，通过独立变更申请产生新版本。'],
 report:['B和E为非负整数；其他原因必填，无情况填“无”。','E＜B必填减少类型、主要原因及说明；其他原因字段独立选填。','待审与已通过只读；重提重新走市省两级；过期须有补报授权。'],
 review:['仅单条审核，无批量审批。','市级通过直接转省级；省级退回直接到企业。','月报退回备注选填，最多500字；备案退回理由必填。'],
 stats:['原始口径默认；修订口径只采用生效修订。','甲100/80、乙50/60：企业2，B150，E140，变化−10，减少20，比例−6.67%。','甲修订E85后：原始仍140，修订145，变化−5，减少15，比例−3.33%。'],
 exchange:['本原型只演示MOCK，本地回执不能证明国家接收。','REAL缺真实地址、凭据及适配时明确未配置，不切回模拟。','未知先查回执；部分拒绝保留已接受结果，失败项修订后单独补发。'],
 correction:['保存修订不生效；生效与撤销是独立动作。','原报表、历史提交及冻结批次不被更正覆盖。'],
 trash:['发送中或结果未知批次引用的报表不能删除。','逻辑删除退出统计，已完成批次仍可复算；恢复不自动报送。'],
 users:['账号忽略大小写唯一；初次改随机初始口令。','有本人提交记录禁止删除；省级默认可导出账号。'],
 roles:['企业、市级、省级业务身份互斥。','企业和市级禁止导出；管理员无隐式业务修改权限。'],
 compare:['共同样本按较晚月份的资料分组。','独立样本各期独立取值，新增与缺失分别标识。'],
 trend:['缺月不是0；折线在缺失处断开。','季度仅筛选三个月，不聚合季度人数。']
};
let S,route='guide',activeId='A',basis='ORIGINAL',cityFilter='',queryText='',queryTab='reports',sampleMode='common',profileEditing=false,journey=-1,modalKind='',dirty=false;
let notes=[];try{notes=JSON.parse(localStorage.getItem('yn-prototype-review-notes')||'[]')}catch{}
const profile=(id)=>({name:'示例企业'+(id==='A'?'甲':'乙'),codeType:'ORG9',enterpriseCode:id==='A'?'A12345678':'B12345678',cityCode:id==='A'?'YN-C01':'YN-C02',countyCode:id==='A'?'YN-C01-K01':'YN-C02-K01',zoneCode:'URBAN',natureParent:'N3',natureCode:'N301',industryParent:'I2',industryCode:'I201',business:'示例制造及配套服务',contactName:'示例联系人',addressCity:id==='A'?'YN-C01':'YN-C02',addressCounty:id==='A'?'YN-C01-K01':'YN-C02-K01',addressDetail:'示例园区1号',postalCode:'000001',phone:'13800000001',fax:'0871-12345678',email:''});
const newReport=(id,E,status='DRAFT')=>({id,period:'2026-09',B:id==='A'?100:50,E,otherReason:'无',reductionType:E<(id==='A'?100:50)?'RT03':'',primaryReason:E<(id==='A'?100:50)?'RC04':'',primaryDescription:E<(id==='A'?100:50)?'示例订单减少导致岗位下降':'',secondaryReason:'',secondaryDescription:'',tertiaryReason:'',tertiaryDescription:'',status,submissionVersion:status==='DRAFT'?0:1,version:1,profileVersion:1,profile:profile(id),snapshots:[],revision:null,revisionDraft:null,returnReason:'',deleted:false,deletedAt:null,submittedAt:status==='DRAFT'?null:'2026-10-05 09:00',approvedAt:status==='APPROVED'?'2026-10-05T02:00:00Z':null,events:[]});
function seed(scenario='daily'){
 S={role:'enterprise',scenario,now:scenario==='late'?'2026-10-12 10:00':'2026-10-06 10:00',open:scenario!=='late',periodStart:'2026-10-01T00:00',periodEnd:'2026-10-11T00:00',firms:{A:{id:'A',uuid:'00000000-0000-4000-8000-000000000001',profile:profile('A'),draft:profile('A'),filing:scenario==='onboarding'?'DRAFT':'APPROVED',profileVersion:1,change:null,baselineLocked:scenario!=='onboarding',baseline:100},B:{id:'B',uuid:'00000000-0000-4000-8000-000000000002',profile:profile('B'),draft:profile('B'),filing:'APPROVED',profileVersion:1,change:null,baselineLocked:true,baseline:50}},reports:{A:newReport('A',80,scenario==='stats'||scenario==='exchange'?'APPROVED':'DRAFT'),B:newReport('B',60,'APPROVED')},batches:[],supplements:[],notices:[{id:'n1',title:'2026年9月企业月报填报提醒',body:'请在2026年10月11日00:00前提交月报。就业人数减少时，请填写减少类型、主要原因及说明。\n无其他情况时，“其他原因”填写“无”。',author:'省级业务甲',createdAt:'2026-10-01 09:00',deleted:false}],users:[{id:'u1',login:'qy_a',type:'企业',firm:'A',roles:['企业'],enabled:true},{id:'u2',login:'qy_b',type:'企业',firm:'B',roles:['企业'],enabled:true},{id:'u3',login:'city_a',type:'市级',city:'YN-C01',roles:['市级审核'],enabled:true},{id:'u4',login:'province_a',type:'省级',roles:['省级业务'],enabled:true},{id:'u5',login:'admin_demo',type:'系统管理',roles:['系统管理'],enabled:true}],accountExport:false,logs:[],customRole:true,dictDisabled:[],monitorFailed:false};
 if(scenario==='onboarding')S.reports.A=null;
 for(const r of Object.values(S.reports).filter(Boolean)){if(r.submissionVersion){r.snapshots.push(snapshot(r));r.events.push({action:'企业提交',who:r.id==='A'?'企业甲':'企业乙',at:r.submittedAt,reason:''});if(r.status==='APPROVED')r.events.push({action:'市、省审核通过',who:'示例审核账号',at:'2026-10-05 10:00',reason:''})}}
 basis='ORIGINAL';cityFilter='';queryText='';profileEditing=false;dirty=false;activeId='A';
}
function snapshot(r){return {version:r.submissionVersion,B:r.B,E:r.E,otherReason:r.otherReason,reductionType:r.reductionType,primaryReason:r.primaryReason,primaryDescription:r.primaryDescription,secondaryReason:r.secondaryReason,secondaryDescription:r.secondaryDescription,tertiaryReason:r.tertiaryReason,tertiaryDescription:r.tertiaryDescription,profile:copy(r.profile),at:r.submittedAt,status:r.status}}
const firm=()=>S.firms[activeId]||S.firms.A;
const rep=()=>S.reports[activeId];
const cityName=c=>c==='YN-C01'?'示例市甲':'示例市乙';
const countyName=c=>c==='YN-C01-K01'?'示例县甲':'示例县乙';
function scopedReports(){return Object.values(S.reports).filter(Boolean).filter(r=>S.role==='enterprise'?r.id==='A':S.role==='city'?r.profile.cityCode==='YN-C01':true)}
function validReports(){return Object.values(S.reports).filter(r=>r&&r.status==='APPROVED'&&!r.deleted&&(!cityFilter||r.profile.cityCode===cityFilter))}
function effective(r){return basis==='CORRECTED'&&r.revision?.active?{...r,...r.revision.data}:r}
function totals(rows){let B=0,E=0,L=0;rows.forEach(raw=>{const r=effective(raw);B+=Number(r.B);E+=Number(r.E);L+=Math.max(r.B-r.E,0)});return{N:rows.length,B,E,D:E-B,L,R:B===0?null:(E-B)/B*100}}
const pct=v=>v===null?'不可计算':(Math.round((v+Math.sign(v||1)*Number.EPSILON)*100)/100).toFixed(2)+'%';
function log(action,obj,reason='',before='',after=''){S.logs.unshift({id:'EV-'+String(S.logs.length+1).padStart(4,'0'),at:S.now,who:roles[S.role]+'演示账号',action,obj,reason,before,after})}
function event(r,action,reason=''){r.events.push({action,who:roles[S.role]+'演示账号',at:S.now,reason})}
function canEdit(r){return S.firms.A.filing==='APPROVED'&&(!r||['DRAFT','CITY_RETURNED','PROVINCE_RETURNED'].includes(r.status))&&!r?.deleted&&(S.open||S.supplements.some(x=>x.id==='A'&&new Date(x.end.replace(' ','T')+'+08:00')>new Date(S.now.replace(' ','T')+'+08:00')))}
const btn=(label,action,kind='',disabled=false,id='')=>`<button type="button" class="${kind}" data-action="${action}" ${id?`data-id="${esc(id)}"`:''} ${disabled?'disabled':''}>${label}</button>`;
function options(list,value,empty=true){return(empty?'<option value="">请选择</option>':'')+list.map(x=>{const val=Array.isArray(x)?x[0]:x.code,name=Array.isArray(x)?x[1]:x.name;return`<option value="${esc(val)}" ${val===value?'selected':''}>${esc(name)}</option>`}).join('')}
function field(label,name,value='',type='text',hint='',required=false,disabled=false,full=false){return`<div class="field ${full?'full':''}"><label for="${name}">${label}${required?' <span class="required">*</span>':''}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${disabled?'disabled':''} ${type==='number'?'min="0" max="2147483647" step="1"':''}>${hint?`<small>${hint}</small>`:''}</div>`}
function selectField(label,name,list,value,hint='',required=false,disabled=false){return`<div class="field"><label for="${name}">${label}${required?' <span class="required">*</span>':''}</label><select id="${name}" name="${name}" ${disabled?'disabled':''}>${options(list,value)}</select>${hint?`<small>${hint}</small>`:''}</div>`}
function area(label,name,value='',hint='',required=false,disabled=false){return`<div class="field full"><label for="${name}">${label}${required?' <span class="required">*</span>':''}</label><textarea id="${name}" name="${name}" ${disabled?'disabled':''}>${esc(value)}</textarea>${hint?`<small>${hint}</small>`:''}</div>`}
const pair=(k,v)=>`<div class="pair"><span>${esc(k)}</span><strong>${v}</strong></div>`;
const empty=(title,text,action='')=>`<div class="empty"><strong>${title}</strong><p>${text}</p>${action}</div>`;
const header=(id,action='')=>`<div class="page-head"><div><h1>${meta[id][0]}</h1><p>${meta[id][1]}</p></div><div class="actions">${action}</div></div>`;
const table=(heads,rows)=>`<div class="table-wrap"><table class="data wide"><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const tr=cells=>'<tr>'+cells.map(c=>'<td>'+c+'</td>').join('')+'</tr>';
const summary=(values)=>`<div class="grid ${values.length===6?'three':'four'}" style="margin-bottom:20px">${values.map(([label,val,unit,desc])=>`<div class="card stat"><span class="muted">${label}</span><div class="value ${String(val).length>7?'small-value':''}">${esc(val)} <span class="unit">${unit||''}</span></div><div class="delta">${desc||''}</div></div>`).join('')}</div>`;
const journeySteps=[['省级建账号','province','users','企业地区与账号已预置；可查看或新增示例账号。'],['企业提交备案','enterprise','profile','核对完整资料，点击“提交备案”。'],['省级审核备案','province','filing','打开示例企业甲，核对资料后通过。'],['企业提交月报','enterprise','report','填B100、E80，补充减少原因并提交。'],['市级审核','city','review','单条通过；通过后立即转省级待审。'],['省级审核','province','review','通过后进入统计与报送有效样本。'],['统计与修订','province','stats','查看140的原始总人数；可另建修订演示145。'],['模拟报送','province','exchange','创建冻结批次，模拟发送并查看回执。']];
function shell(){const [title]=meta[route];$('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">YN</div><div><strong>企业就业监测</strong><small>云南省 · 需求交互原型</small></div></div><div class="nav-label">${roles[S.role]}工作空间</div><nav class="nav" aria-label="工作台导航">${menus[S.role].map(id=>`<button class="nav-item ${id===route?'active':''}" data-go="${id}" ${id===route?'aria-current="page"':''}>${meta[id][0]}${id==='guide'?'<span>↗</span>':''}</button>`).join('')}</nav><div class="sidebar-bottom">需求 SRS V1.2 · 界面主体 V1.1<br>示例企业与地区均为合成数据<br>界面与交互用于需求方向评审</div></aside><div class="main"><header class="topbar"><div class="topbar-left"><span class="topbar-title">云南省企业就业失业数据采集系统</span><span class="tag">交互原型</span></div><div class="top-controls"><label for="role-switch">角色</label><select id="role-switch" aria-label="切换演示角色">${Object.entries(roles).map(([key,name])=>`<option value="${key}" ${S.role===key?'selected':''}>${name}${key==='city'?' · 示例市甲':''}</option>`).join('')}</select><label for="scenario-switch">场景</label><select id="scenario-switch" aria-label="切换演示场景">${[['daily','日常填报'],['onboarding','首次备案'],['stats','统计复算'],['late','过期补报'],['exchange','报送异常']].map(([v,n])=>`<option value="${v}" ${S.scenario===v?'selected':''}>${n}</option>`).join('')}</select>${btn('页面评审说明','help','small')}${btn('重置演示','reset','small')}</div></header>${journey>=0?`<section class="journey"><div><strong>业务演示 ${journey+1} / 8 · ${journeySteps[journey][0]}</strong><p>${journeySteps[journey][3]}</p></div><div class="actions">${btn('上一步','journey-prev','small',journey===0)}${btn(journey===7?'完成导览':'下一步','journey-next','primary small')}${btn('退出导览','journey-exit','small')}</div></section>`:''}<main class="content" id="main"><div class="breadcrumb">${roles[S.role]} / ${title} <span style="float:right">演示时间 ${S.now} · 上海时区</span></div>${renderPage()}</main></div></div>`;document.title=title+' · 云南企业就业监测原型';dirty=false}
function go(id){if(dirty){modal('离开未保存页面','<p>当前输入尚未保存。离开后将显示上次保存的数据。</p>',btn('继续编辑','close')+`<button class="danger" data-leave="${id}">放弃本次输入并离开</button>`);return}if(!menus[S.role].includes(id)&&id!=='login'){toast('当前角色无权进入此页面');return}route=id;shell();window.scrollTo(0,0)}
function toast(text){$('#toast').textContent=text;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500)}
function modal(title,body,footer=''){modalKind=title;$('#dialog').innerHTML=`<div class="modal-content"><div class="modal-head"><h2 id="dialog-title">${title}</h2>${btn('关闭','close','small')}</div>${body}<div class="modal-footer">${footer||btn('知道了','close','primary')}</div></div>`;if(!$('#dialog').open)$('#dialog').showModal()}
function close(){if($('#dialog').open)$('#dialog').close();$('#dialog').innerHTML=''}
function errorMessages(messages){const box=$('#modal-errors')||$('#form-errors');if(box){box.innerHTML=messages.map(x=>'<div>'+esc(x)+'</div>').join('');box.scrollIntoView({block:'nearest'});}else toast(messages.join('；'))}
function renderPage(){return({guide:guidePage,dashboard:dashboardPage,profile:profilePage,filing:filingPage,report:reportPage,review:reviewPage,history:historyPage,archives:archivesPage,query:queryPage,stats:statsPage,compare:comparePage,trend:trendPage,correction:correctionPage,supplement:supplementPage,exchange:exchangePage,notices:noticesPage,users:usersPage,roles:rolesPage,periods:periodsPage,dict:dictPage,monitor:monitorPage,audit:auditPage,trash:trashPage,login:loginPage})[route]()}

function guidePage(){return `<section class="card hero"><div><div class="eyebrow">PROJECT GUIDE / 首次接触项目，从这里开始</div><h1>把企业月度就业变化<br>变成可审核、可复算的数据</h1><p>企业填报 → 市级审核 → 省级审核 → 汇总分析与报送。<br>所有关键版本保留，让每个数字都能解释清楚。</p><div class="actions">${btn('开始完整业务演示 →','start-journey','primary')}${btn('查看登录界面','login-view','ghost')}</div></div><div class="hero-side"><div><strong>采集什么</strong><span>企业资料、建档人数B、当月就业人数E、减少原因</span></div><div><strong>产出什么</strong><span>已审核月报、月度统计、版本记录、报送批次与回执</span></div><div><strong>本期边界</strong><span>不计算个人失业率；不做保险核算、短信或预测</span></div></div></section><div class="grid four">${[['enterprise','企业','维护资料，填报与重提','只看自身企业，不提供导出'],['city','市级审核','核对辖区报表，通过或退回','通过后自动转省，无另行发送'],['province','省级业务','备案、省审、统计、报送及系统管理','账号、角色、调查期、监控和三类导出均可用'],['admin','系统管理','账号、角色、调查期、字典与监控','管理角色不隐含业务修改权']].map(([r,n,task,limit])=>`<section class="card role-card"><h3>${n}</h3><p>${task}<br><br>${limit}</p><button data-role-go="${r}" data-target="dashboard">进入${n}工作台 →</button></section>`).join('')}</div><section class="card section-gap"><h2>一条完整业务链，八个明确交接点</h2><div class="flow">${journeySteps.map(([name,r,id,desc],i)=>`<div class="flow-item"><span class="number">STEP ${String(i+1).padStart(2,'0')} · ${roles[r]}</span><strong>${name}</strong><p>${desc}</p></div>`).join('')}</div></section><div class="grid two"><section class="card"><h2>三种容易误解的规则</h2><div class="pair"><span>审核退回</span><strong>省级直接退给企业；重新提交后，重新走市、省两级。</strong></div><div class="pair"><span>数据修订</span><strong>另存并显式生效；原始值与已经冻结的报送数据保持不变。</strong></div><div class="pair"><span>国家报送</span><strong>模拟回执只证明原型场景；实际接入需要真实地址、凭据和协议。</strong></div></section><section class="card"><h2>建议评审顺序</h2><p>先走通完整业务链，再用顶部“场景”查看统计复算、过期补报和报送异常。</p><p>在任意页面打开“页面评审说明”，查看需求对应关系、关键规则，并记录希望保留或调整的界面方向。</p><div class="actions">${btn('查看原型边界','boundaries')}${btn('方向记录 '+notes.length+' 条','notes-view')}</div></section></div><section class="card"><h2>暂时性实施规划 · 当前采用的默认方向</h2><p class="muted">这些规则已经体现在界面中，可先按此方向讨论。调整通过页面评审记录留下影响范围。</p>${[['权限与流程','三类业务身份互斥；省级默认具备全部业务和管理能力，市审通过自动转省。'],['资料与编码','企业可补录及申请变更组织机构代码，1至9位字母数字；姓名限中文英文，传真必填固话。'],['月报与原因','B首次提交锁定；其他原因必填，无情况填“无”；减少时三项必填，其他原因与说明独立选填，未来基准不改历史。'],['统计与查询','六项指标、双口径、共同样本默认、季度只筛月；查询交集与全量导出。'],['退回与补报','省审直接退企业，月报备注选填，重新走两级审核；默认补报72小时，最多7天。'],['字典、保留与质量','示例地区及应用内分类；删除30日内恢复；5年在线归档；合成数据验证性能、安全与恢复。'],['交换边界','MOCK只作阶段验证；最终必须交付REAL适配与实际接收凭据，页面明确未完成项。']].map(([t,p])=>`<details><summary>${t}</summary><p>${p}</p></details>`).join('')}</section>`}
function dashboardPage(){const rows=scopedReports(),pending=rows.filter(r=>r.status===(S.role==='city'?'CITY_PENDING':'PROVINCE_PENDING')).length;const enterprise=S.role==='enterprise';return header('dashboard',btn('按完整业务链体验','start-journey','primary'))+`<div class="callout"><strong>${enterprise?'当前任务：'+(S.firms.A.filing!=='APPROVED'?'先完成企业备案':'填报2026年9月就业人数'):S.role==='admin'?'当前任务：保证账号、调查期和字典可用':'当前任务：逐条处理待审记录，保留理由与版本'}</strong><br>${S.open?'填报窗口：'+S.periodStart.replace('T',' ')+' — '+S.periodEnd.replace('T',' ')+'（不含截止）':'默认填报窗口已关闭；企业须获得指定期别补报授权。'}</div>`+summary(enterprise?[['备案状态',statuses[S.firms.A.filing][0],'','月报前置条件'],['当期状态',S.reports.A?statuses[S.reports.A.status][0]:'未建报','','2026年9月'],['建档人数',100,'人','首次提交后锁定'],['窗口状态',S.open?'开放':'已关闭','','上海时区判定']]:[['企业档案',Object.keys(S.firms).length,'家','全部为合成企业'],['本角色待审',S.role==='admin'?'—':pending,'条','只提供单条审批'],['已通过月报',validReports().length,'条','当前原始口径'],['模拟批次',S.batches.length,'个','MOCK与REAL分别展示']])+`<div class="grid two"><section class="card"><h2>快速进入</h2>${menus[S.role].filter(id=>!['guide','dashboard','audit'].includes(id)).slice(0,5).map(id=>`<button class="screen-link" data-go="${id}"><strong>${meta[id][0]}</strong><span>${meta[id][1].slice(0,22)} →</span></button>`).join('')}</section><section class="card"><h2>当前数据范围</h2>${pair('演示身份',roles[S.role])}${pair('可访问范围',enterprise?'示例企业甲':S.role==='city'?'示例市甲及示例县甲':S.role==='province'?'全省示例企业':'用户、配置和运行数据')}${pair('导出能力',enterprise||S.role==='city'?'禁止导出':S.role==='province'?'企业、月报与账号':'账号导出需单独授权')}${pair('最近通知',esc(S.notices.find(n=>!n.deleted&&(S.role!=='province'||n.authorId===authorId()))?.title||'无有效通知'))}</section></div>`}
function profileForm(p,disabled){return `<div class="form-section"><h3>01 · 企业与归属</h3><div class="form-grid">${field('所属市','cityDisplay',cityName(p.cityCode),'text','由管理员分配，企业不可修改',false,true)}${field('所属县','countyDisplay',countyName(p.countyCode),'text','示例地区编码，仅用于原型',false,true)}${field('区域','zoneDisplay',({URBAN:'城区',COUNTY:'县域',RURAL:'乡村'}[p.zoneCode]||p.zoneCode),'text','',false,true)}${field('企业名称','name',p.name,'text','1至200字',true,disabled)}${field('编码类型','codeDisplay',p.codeType==='ORG9'?'组织机构代码 ORG9':'统一社会信用代码 USCC18','text','编码由管理纠错入口维护',false,true)}${field('企业编码','codeValue',p.enterpriseCode,'text','按字符串保存，保留前导零',false,true)}${selectField('性质父级','natureParent',Object.entries(nature).map(([k,v])=>[k,v[0]]),p.natureParent,'',true,disabled)}${selectField('性质子级','natureCode',(nature[p.natureParent]?.[1]||[]),p.natureCode,'子级必须属于父级',true,disabled)}${selectField('行业父级','industryParent',Object.entries(industry).map(([k,v])=>[k,v[0]]),p.industryParent,'',true,disabled)}${selectField('行业子级','industryCode',(industry[p.industryParent]?.[1]||[]),p.industryCode,'应用内分类，不冒充外部标准',true,disabled)}${area('经营业务','business',p.business,'1至500字',true,disabled)}</div></div><div class="form-section"><h3>02 · 联系方式</h3><div class="form-grid">${field('联系人','contactName',p.contactName,'text','1至50字',true,disabled)}${field('邮编','postalCode',p.postalCode,'text','6位数字，按文本保存',true,disabled)}${selectField('地址市','addressCity',[['YN-C01','示例市甲'],['YN-C02','示例市乙']],p.addressCity,'可不同于经营地区',true,disabled)}${selectField('地址县','addressCounty',[[p.addressCity+'-K01',countyName(p.addressCity+'-K01')]],p.addressCounty,'',true,disabled)}${field('详细地址','addressDetail',p.addressDetail,'text','1至200字',true,disabled,true)}${field('电话','phone',p.phone,'text','国内手机号或带区号固定电话',true,disabled)}${field('传真','fax',p.fax,'text','无传真填写“无”',true,disabled)}${field('邮箱','email',p.email,'text','选填；不发送验证邮件',false,disabled)}</div></div>`}
function profilePage(){activeId='A';const f=firm(),pending=f.change?.status==='PENDING'||f.filing==='PENDING',approved=f.filing==='APPROVED',editable=(!approved||profileEditing)&&!pending,p=approved&&!profileEditing?f.profile:f.draft;return header('profile',badge(f.change?.status==='PENDING'?'PENDING':f.filing))+`<div class="callout ${pending?'warning':approved?'success':''}">${pending?'资料正在待审，不能覆盖；变更待审时，已通过旧档案继续生效。':approved?'备案已通过。当前生效资料版本 v'+f.profileVersion+'；资料变更不会改写已经提交的月报。':'首次备案：完整填写资料并提交；省级通过后开放月报。'}${(f.filing==='RETURNED'||f.change?.status==='RETURNED')?'<br>退回理由：'+esc(f.filingReason):''}</div><div class="card"><form id="profile-form"><div id="form-errors" class="errors" role="alert"></div>${profileForm(p,!editable)}<div class="form-actions">${approved&&!profileEditing&&!pending?btn('申请资料变更','profile-edit','primary'):editable?btn('保存草稿','profile-save')+btn(approved?'提交变更申请':'提交备案','profile-submit','primary'):btn('查看已提交资料','profile-preview')}</div></form></div>`}
function filingPage(){const pending=Object.values(S.firms).filter(f=>f.filing==='PENDING'||f.change?.status==='PENDING');return header('filing')+`<div class="card">${pending.length?table(['企业','申请类型','资料版本','状态','操作'],pending.map(f=>tr([esc(f.profile.name),f.change?'资料变更':'首次备案','v'+f.profileVersion,badge('PENDING'),btn('查看并审核','filing-detail','small',false,f.id)]))):empty('暂无待备案申请','切换企业角色提交资料，或开始完整业务演示。',btn('去企业资料页面','to-enterprise-profile','primary'))}</div>`}
function reportPage(){activeId='A';const f=firm(),r=rep(),allowed=canEdit(r),data=r||newReport('A',80);if(f.filing!=='APPROVED')return header('report')+`<div class="card">${empty('企业尚未完成备案','请先提交完整资料，并由省级通过备案。',btn('去维护企业资料','go-profile','primary'))}</div>`;const disabled=!allowed,red=data.E<data.B,stage=data.status==='APPROVED'?3:data.status==='PROVINCE_PENDING'?2:data.status==='CITY_PENDING'?1:0;return header('report',badge(r?.status||'DRAFT'))+`<div class="stepper">${[['企业填报','DRAFT'],['市级审核','CITY_PENDING'],['省级审核','PROVINCE_PENDING'],['完成','APPROVED']].map(([n,s],i)=>`<div class="step ${i===stage?'current':i<stage?'done':''}"><span class="num">${i+1}</span>${n}</div>`).join('')}</div>${!S.open?`<div class="callout warning">填报窗口已关闭。${allowed?'当前有有效补报授权，可以编辑与提交。':'请由省级对本企业、本月份授权补报。'}</div>`:''}${data.status.includes('RETURNED')?`<div class="callout warning"><strong>审核退回：</strong>${esc(data.returnReason||'未填写备注')}<br>重新提交后再次进入市级审核，不继承旧审核结果。</div>`:''}${disabled?'<div class="callout">当前版本只读；保存与提交仅允许在开放或补报窗口内的草稿、退回状态。</div>':''}<div class="grid two"><div class="card" style="grid-column:1/-1"><div class="split-summary"><h2>2026年9月 · ${esc(disabled&&r?.submissionVersion?r.profile.name:f.profile.name)}</h2><span class="muted">资料v${disabled&&r?.submissionVersion?r.profileVersion:f.profileVersion} · 提交v${data.submissionVersion} · 截止${esc(S.periodEnd.replace('T',' '))}</span></div><form id="report-form"><div id="form-errors" class="errors" role="alert"></div><div class="form-grid">${field('建档人数 B','B',data.B,'number',f.baselineLocked?'基准已锁定；历史纠错由省级独立修订':'首次正式提交后锁定',true,disabled||f.baselineLocked)}${field('调查人数 E','E',data.E,'number','0至2,147,483,647的整数',true,disabled)}<div class="field full"><div id="change-summary" class="callout ${red?'warning':''}" style="margin:0">本期岗位变化：${data.E-data.B} 人；岗位减少：${Math.max(data.B-data.E,0)} 人。</div></div></div><div id="reduction-fields" style="margin-top:24px"><h3>减少类型与原因 <span class="tag ${red?'amber':'gray'}" id="reason-badge">${red?'当前为减少，主要项必填':'未减少，可不填'}</span></h3><div class="form-grid">${selectField('减少类型','reductionType',rt,data.reductionType,'减少时必填单选',red,disabled)}${selectField('主要原因','primaryReason',rc,data.primaryReason,'人数减少时必填',red,disabled)}${area('主要原因说明','primaryDescription',data.primaryDescription,'人数减少时必填，最多500字',red,disabled)}${selectField('次要原因','secondaryReason',rc,data.secondaryReason,'选填，可独立选择',false,disabled)}${area('次要原因说明','secondaryDescription',data.secondaryDescription,'选填，可独立填写，最多500字',false,disabled)}${selectField('第三原因','tertiaryReason',rc,data.tertiaryReason,'选填，可独立选择',false,disabled)}${area('第三原因说明','tertiaryDescription',data.tertiaryDescription,'选填，可独立填写，最多500字',false,disabled)}${area('其他原因','otherReason',data.otherReason,'额外说明1至500字；没有情况填写“无”，不能代替上面的原因说明',true,disabled)}</div></div><div class="form-actions">${btn('保存草稿','report-save','',disabled)}${btn(data.status.includes('RETURNED')?'重新提交至市级':'提交至市级审核','report-submit','primary',disabled)}</div></form></div></div>`}
function reportRows(rows,action='detail'){return rows.map(r=>tr([esc(r.profile.name),cityName(r.profile.cityCode),r.period,`${r.B} / ${r.E}`,badge(r.deleted?'DELETED':r.status),'v'+r.submissionVersion,btn(action==='review'?'查看并审核':'查看详情',action==='review'?'review-detail':'report-detail','small',false,r.id)]))}
function reviewPage(){const target=S.role==='city'?'CITY_PENDING':'PROVINCE_PENDING',rows=scopedReports().filter(r=>r.status===target&&!r.deleted);return header('review')+`<div class="callout">${S.role==='city'?'仅示例市甲及下级地区；通过后自动出现在省级待审列表。':'仅接收已通过市审的提交版本；通过后纳入统计与报送。'}月报退回备注选填（最多500字），逐条操作。</div><div class="card"><h2>待审月报 <span class="tag">${rows.length} 条</span></h2>${rows.length?table(['企业','所属市','月份','B / E','状态','提交版本','操作'],reportRows(rows,'review')):empty('暂无待审月报','企业提交后进入市审；市审通过后进入省审。')}</div>`}
function historyPage(){const rows=scopedReports().filter(r=>r.submissionVersion&&!r.deleted);return header('history')+`<div class="card">${rows.length?table(['企业','所属市','月份','B / E','状态','提交版本','操作'],reportRows(rows)):empty('暂无已提交历史','保存草稿还不是正式提交记录。')}</div>`}
function archivesPage(){const rows=Object.values(S.firms).filter(f=>f.filing==='APPROVED');return header('archives',btn('导出预览','export-preview'))+`<div class="card"><div class="filters"><div class="field"><label for="archive-basis">资料范围</label><select id="archive-basis"><option>当前生效档案</option><option>2026年9月提交快照</option></select></div><div class="field"><label for="archive-search">企业名称</label><input id="archive-search" placeholder="输入名称关键词"></div>${btn('查询','archive-search')}</div>${table(['企业','编码','所属市县','性质 / 行业','版本','操作'],rows.map(f=>tr([esc(f.profile.name),esc(f.profile.enterpriseCode),cityName(f.profile.cityCode)+' / '+countyName(f.profile.countyCode),nameOf(nature,f.profile.natureCode)+' / '+nameOf(industry,f.profile.industryCode),'v'+f.profileVersion,btn('只读详情','archive-detail','small',false,f.id)])))}</div>`}
function reportDetail(r,review=false){const f=S.firms[r.id];return `<div class="callout">${esc(r.profile.name)} · ${r.period} · 提交v${r.submissionVersion} · 资料快照v${r.profileVersion} ${badge(r.status)}</div><div class="grid two"><div>${pair('建档人数 B',r.B+' 人')}${pair('调查人数 E',r.E+' 人')}${pair('岗位变化',r.E-r.B+' 人')}${pair('减少类型',codeName(rt,r.reductionType))}${pair('主要原因',codeName(rc,r.primaryReason))}${pair('主要说明',esc(r.primaryDescription||'—'))}${pair('次要 / 第三原因',esc([codeName(rc,r.secondaryReason),codeName(rc,r.tertiaryReason)].join(' / ')))}${pair('次要原因说明',esc(r.secondaryDescription||'—'))}${pair('第三原因说明',esc(r.tertiaryDescription||'—'))}${pair('其他原因',esc(r.otherReason))}</div><div>${pair('所属地区',cityName(r.profile.cityCode)+' / '+countyName(r.profile.countyCode))}${pair('企业编码',esc(r.profile.enterpriseCode))}${pair('性质 / 行业',nameOf(nature,r.profile.natureCode)+' / '+nameOf(industry,r.profile.industryCode))}${pair('提交时间',esc(r.submittedAt||'未提交'))}${pair('修订状态',r.revision?.active?'v'+r.revision.version+'已生效；E='+r.revision.data.E:'无生效修订')}${pair('备案状态',badge(f.filing))}</div></div><h3 class="section-gap">审核与退回记录</h3><div class="timeline">${r.events.map(e=>`<div class="timeline-item"><strong>${esc(e.action)}</strong><small> · ${esc(e.at)} · ${esc(e.who)}</small>${e.reason?'<p>'+esc(e.reason)+'</p>':e.action.includes('退回')?'<p>未填写备注</p>':''}</div>`).join('')||'<p class="muted">尚无正式提交事件。</p>'}</div>${!review?`<h3>历次原始提交</h3>${table(['版本','B / E','资料版本','提交时间'],r.snapshots.map(s=>tr(['v'+s.version,`${s.B} / ${s.E}`,'冻结资料',esc(s.at)])))}`:''}`}

function queryPage(){const rows=Object.values(S.reports).filter(r=>r&&!r.deleted&&r.profile.name.includes(queryText));return header('query',btn('导出全部命中 · 预览','export-preview'))+`<div class="tabs">${btn('企业报表','query-reports',queryTab==='reports'?'selected':'')}${btn('账号查询入口','query-accounts',queryTab==='accounts'?'selected':'')}</div>${queryTab==='accounts'?'<div class="callout">省级兼任系统管理时才可查看账号。当前为独立省级业务角色，请切换系统管理进入账号列表；账号导出仍需单独授权。</div>':`<div class="card"><div class="filters"><div class="field"><label for="query-name">企业名称</label><input id="query-name" value="${esc(queryText)}" placeholder="包含匹配"></div><div class="field"><label for="query-state">状态</label><select id="query-state"><option value="">全部状态</option>${options(['DRAFT','CITY_PENDING','PROVINCE_PENDING','APPROVED'].map(s=>[s,statuses[s][0]]),'',false)}</select></div><div class="field"><label for="query-month">月份</label><input id="query-month" type="month" value="2026-09"></div></div><div class="filters"><div class="field"><label for="query-start">提交开始日</label><input id="query-start" type="date"></div><div class="field"><label for="query-end">提交结束日</label><input id="query-end" type="date"></div><div class="actions">${btn('查询','query-search','primary')}${btn('清除','query-clear')}</div></div><div id="form-errors" class="errors" role="alert"></div><div id="query-results">${table(['企业','所属市','月份','B / E','状态','提交版本','操作'],reportRows(rows))}</div><div class="table-note"><span id="query-total">共 ${rows.length} 条 · 条件取交集 · 提交日期包含结束日全天</span><span>每页20条 · 时间降序，标识降序</span></div></div>`}`}
function statsFilters(){return `<div class="filters"><div class="field"><label for="data-basis">统计口径</label><select id="data-basis"><option value="ORIGINAL" ${basis==='ORIGINAL'?'selected':''}>原始有效口径（默认）</option><option value="CORRECTED" ${basis==='CORRECTED'?'selected':''}>修订有效口径</option></select></div><div class="field"><label for="stats-city">地区</label><select id="stats-city"><option value="">全部示例市</option>${options([['YN-C01','示例市甲'],['YN-C02','示例市乙']],cityFilter,false)}</select></div><div class="field"><label for="stats-period">调查月份</label><input id="stats-period" type="month" value="2026-09" disabled></div></div>`}
function statsPage(){const rows=validReports(),t=totals(rows);return header('stats',btn('导出统计预览','export-preview'))+`<div class="card">${statsFilters()}<div class="pill-row"><span class="tag">${basis==='ORIGINAL'?'原始有效口径':'修订有效口径'}</span><span class="tag gray">公式版本1</span><span class="tag gray">省审通过、未删除</span></div></div>`+summary([['有效企业数',t.N,'家','每企业每期唯一'],['建档总岗位 B',t.B,'人','同一有效样本ΣB'],['调查总岗位 E',t.E,'人','同一有效样本ΣE'],['岗位变化',t.D,'人','E−B，保留正负'],['岗位减少',t.L,'人','逐企业max(B−E,0)求和'],['变化比例',pct(t.R),'','(E−B)÷B×100%']])+`<div class="grid two"><section class="card"><h2>各市取样企业占比</h2>${t.N?['YN-C01','YN-C02'].map(c=>{const n=rows.filter(r=>r.profile.cityCode===c).length,p=n/t.N*100;return`<div class="bar-row"><span>${cityName(c)}</span><div class="bar-track"><div class="bar-fill" style="width:${p}%"></div></div><strong>${n}家 / ${pct(p)}</strong></div>`}).join(''):empty('没有有效样本','暂无省审通过且未删除的报表。')}<small>各市以当前有效样本为分母；显示值存在舍入尾差。</small></section><section class="card"><h2>企业复算明细</h2>${table(['企业','B','E','变化','减少'],rows.map(raw=>{const r=effective(raw);return tr([esc(r.profile.name),r.B,r.E,r.E-r.B,Math.max(r.B-r.E,0)])}))}<p class="muted section-gap">生效修订只影响修订口径。已冻结的批次保持建批时的数据。</p>${btn('另存数据修订','go-correction')}</section></div>`}
function comparePage(){const current=validReports(),common=current.filter(r=>r.id==='A'),used=sampleMode==='common'?common:current;const old=common.map(r=>({...r,E:90,revision:null,period:'2026-08'})),a=totals(old),b=totals(used);return header('compare')+`<div class="card"><div class="filters"><div class="field"><label>对比月份</label><input type="month" value="2026-08" disabled></div><div class="field"><label>调查月份</label><input type="month" value="2026-09" disabled></div><div class="field"><label for="sample-mode">样本方式</label><select id="sample-mode"><option value="common" ${sampleMode==='common'?'selected':''}>共同企业（默认）</option><option value="independent" ${sampleMode==='independent'?'selected':''}>各期独立样本</option></select></div></div><div class="callout">示例8月仅甲有记录。9月乙为新增企业，不把缺失记录当0。共同样本使用较晚月份资料分组；独立样本使用各期资料分组。</div>${table(['指标','2026年8月','2026年9月'],[['企业数 N',a.N,b.N],['建档总岗位 B',a.B,b.B],['调查总岗位 E',a.E,b.E],['岗位变化',a.D,b.D],['岗位减少',a.L,b.L],['变化比例',pct(a.R),pct(b.R)]].map(tr))}<div class="pill-row section-gap"><span class="tag">9月新增 ${current.filter(r=>r.id==='B').length} 家</span><span class="tag gray">9月缺失 ${current.some(r=>r.id==='A')?0:1} 家</span><span class="tag gray">分组：性质、行业、地区的示例资料</span></div><small>本页样例侧重样本方向；生产维度联动与多月任意筛选需在正式实现中完成。</small></div>`}
function trendPage(){const v=totals(validReports()).R;return header('trend')+`<div class="card"><h2>2026年6月—9月 · 变化比例</h2><svg class="chart" viewBox="0 0 800 220" role="img" aria-label="变化比例趋势，7月缺失，折线在缺失月份断开"><line x1="50" y1="170" x2="750" y2="170"/><line x1="50" y1="60" x2="750" y2="60"/><text x="4" y="64">0%</text><text x="4" y="174">−10%</text><circle cx="100" cy="104" r="6"/><polyline points="490,115 690,${v===null?170:60-Math.max(-10,Math.min(0,v))*11}"/>${v!==null?`<circle cx="690" cy="${60-Math.max(-10,Math.min(0,v))*11}" r="6"/>`:''}<circle cx="490" cy="115" r="6"/><text x="80" y="205">6月 −4%</text><text x="277" y="205">7月 缺失</text><text x="463" y="205">8月 −5%</text><text x="651" y="205">9月 ${pct(v)}</text><text x="285" y="105">缺失 · 断线</text></svg>${table(['月份','样本说明','变化比例'],[['2026-06','趋势演示样本','−4.00%'],['2026-07','缺失','不可计算'],['2026-08','趋势演示样本','−5.00%'],['2026-09','当前已通过样本',pct(v)]].map(tr))}<p class="muted section-gap">6月与8月为独立趋势示例。当前9月取本轮模拟业务数据；缺月不插值。季度仅筛选三个月，不累加人数。</p></div>`}
function correctionPage(){const rows=validReports();return header('correction',btn('未来基准规划','baseline-new'))+`<div class="callout">保存修订 → 核对前后值 → 另行生效。撤销本次生效后恢复上一有效修订或原始取值；已经冻结的批次不更新。</div><div class="card">${rows.length?table(['企业','原始 B / E','修订 B / E','状态','操作'],rows.map(r=>tr([esc(r.profile.name),`${r.B} / ${r.E}`,r.revisionDraft?`${r.revisionDraft.data.B} / ${r.revisionDraft.data.E}`:r.revision?`${r.revision.data.B} / ${r.revision.data.E}`:'—',r.revisionDraft?'<span class="tag amber">已保存未生效</span>':r.revision?.active?'<span class="tag green">修订已生效</span>':'无修订',btn('另存修订','correction-edit','small',false,r.id)+(r.revisionDraft?btn('生效','correction-activate','primary small',false,r.id):r.revision?.active?btn('撤销生效','correction-revoke','small',false,r.id):'')]))):empty('暂无可修订报表','仅省审已通过且未删除的报表可修订。')}</div>`}
function supplementPage(){return header('supplement',btn('新增补报授权','supplement-new','primary'))+`<div class="callout">默认72小时，最多168小时。仅解锁指定企业、期别的草稿或退回记录；不解锁待审、已通过和已删除数据。</div><div class="card">${S.supplements.length?table(['企业','月份','开始','截止（不含）','理由','操作'],S.supplements.map(x=>tr([esc(S.firms[x.id].profile.name),x.period,x.start,x.end,esc(x.reason),btn('使授权到期 · 演示','supplement-expire','small',false,x.key)]))):empty('暂无补报授权','切换“过期补报”场景后，新增授权并返回企业填报页面。')}</div>`}
function exchangePage(){return header('exchange',btn('创建冻结批次','batch-create','primary',!validReports().length))+`<div class="callout warning"><strong>当前为需求演示。</strong>MOCK显示“模拟接收成功”；REAL未提供真实地址、凭据与协议，发送明确报未配置。</div><div class="card"><div class="filters"><div class="field"><label for="exchange-mode">交换模式</label><select id="exchange-mode"><option value="MOCK">MOCK · 本地模拟</option><option value="REAL">REAL · 真实接入（未配置）</option></select></div><div class="field"><label for="data-basis">建批数据口径</label><select id="data-basis"><option value="ORIGINAL" ${basis==='ORIGINAL'?'selected':''}>原始有效口径</option><option value="CORRECTED" ${basis==='CORRECTED'?'selected':''}>修订有效口径</option></select></div><div class="field"><label for="mock-receipt">演示接收结果</label><select id="mock-receipt"><option value="success">全部接受</option><option value="partial">部分拒绝</option><option value="unknown">响应超时 / 结果未知</option><option value="unauthorized">认证失败401</option></select></div></div><small>模式、回执场景为原型控制，创建后批次载荷不会随修订变化。</small></div><div class="card"><h2>批次与回执 <span class="tag">${S.batches.length} 个</span></h2>${S.batches.length?table(['批次','模式 / 口径','条数 / E总数','状态','操作'],S.batches.map(b=>tr([`<strong>${esc(b.label)}</strong><br><small>${b.period}</small>`,b.mode+' / '+(b.basis==='ORIGINAL'?'原始':'修订'),b.records.length+' 条 / '+b.records.reduce((a,r)=>a+r.employedCount,0)+' 人',badge(b.status),btn('冻结详情','batch-detail','small',false,b.id)+(b.status==='QUEUED'?btn('发送','batch-send','primary small',false,b.id):b.status==='UNKNOWN'?btn('先查回执','batch-receipt','primary small',false,b.id):b.status==='REJECTED'?btn('失败项补发','batch-retry','small',false,b.id):'')]))):empty('尚未创建报送批次','先完成省审，再按调查期和明确口径建立批次。')}</div>`}
function noticesPage(){return header('notices',S.role==='province'?btn('发布通知','notice-new','primary'):'')+`<div class="card">${S.notices.filter(n=>!n.deleted).map(n=>`<article class="notice"><div class="split-summary"><h3>${esc(n.title)}</h3>${S.role==='province'&&n.author==='省级业务甲'?'<div class="actions">'+btn('修改','notice-edit','small',false,n.id)+btn('删除','notice-delete','danger small',false,n.id)+'</div>':''}</div><div class="meta">发布单位：省级 · ${esc(n.createdAt)} · ${esc(n.author)}</div><p>${esc(n.body)}</p></article>`).join('')||empty('暂无有效通知','删除后的通知不在普通列表和详情中展示。')}</div>`}
function usersPage(){return header('users',btn('新增账号','user-new','primary')+btn('账号导出预览','export-preview','',!S.accountExport))+`<div class="callout">当前系统管理角色仅处理用户、配置和运行信息。账号导出${S.accountExport?'已显式授权':'默认无授权，可在角色页面授予'}。</div><div class="card">${table(['账号','身份 / 归属','角色','状态','操作'],S.users.filter(u=>!u.deleted).map(u=>tr([esc(u.login),u.type+' / '+(u.firm?esc(S.firms[u.firm].profile.name):u.city?cityName(u.city):'全省'),esc(u.roles.join('、')||'无角色'),`<span class="tag ${u.enabled?'green':'gray'}">${u.enabled?'启用':'停用'}</span>`,btn('角色','user-role','small',false,u.id)+btn(u.enabled?'停用':'启用','user-toggle','small',false,u.id)+btn('删除','user-delete','danger small',false,u.id)])))}</div>`}
function rolesPage(){return header('roles',btn('新增角色模板','role-new','primary'))+`<div class="card">${table(['角色','数据范围','功能边界'],[['企业','单一企业','资料、填报、历史、通知；禁止导出'],['市级审核','单一市及下级','单条审核及历史、通知；禁止修订、删除、导出'],['省级业务','全省企业','备案、省审、修订、统计、导出、通知、交换'],['系统管理','账号、配置、运行','无隐式业务修改权限；可显式授权账号导出']].map(tr))}<div class="callout section-gap">企业、市级、省级业务身份互斥。系统管理只能授予独立管理或省级账号；移除角色后下一请求撤权。</div><div class="checks"><label><input id="export-permission" type="checkbox" ${S.accountExport?'checked':''}>向独立系统管理账号显式授予账号导出权限</label></div></div>${S.customRole?`<div class="card"><h3>示例自定义只读角色</h3><p>关联0名用户；可删除模板。已分配模板删除时，必须列影响并二次确认。</p>${btn('删除示例角色','role-delete','danger')}</div>`:''}`}
function periodsPage(){return header('periods')+`<div class="card"><h2>2026年9月 · 企业月报</h2><div class="callout">模板+月份唯一。有报表后月份不可改，起止窗口可调整并审计。开始包含，截止不包含。</div><form id="period-form"><div id="form-errors" class="errors" role="alert"></div><div class="form-grid">${field('调查月份','period','2026-09','month','已有报表，月份锁定',true,true)}${field('开始时间 · 上海时区','periodStart',S.periodStart,'datetime-local','默认本月1日00:00',true)}${field('截止时间 · 上海时区','periodEnd',S.periodEnd,'datetime-local','默认本月11日00:00，不含此时刻',true)}</div><div class="form-actions">${btn('保存调查期配置','period-save','primary')}</div></form></div>`}
function dictPage(){return header('dict',btn('查看配置导入','dict-import'))+`<div class="grid two"><section class="card"><h2>两级性质分类</h2>${Object.entries(nature).map(([k,v])=>`<details><summary>${k} · ${v[0]}</summary>${v[1].map(([c,n])=>`<div class="pair"><span>${c}</span><strong>${n} ${S.dictDisabled.includes(c)?'<span class="tag gray">已停用</span>':btn('停用','dict-disable','small',false,c)}</strong></div>`).join('')}</details>`).join('')}</section><section class="card"><h2>两级行业分类</h2>${Object.entries(industry).map(([k,v])=>`<details><summary>${k} · ${v[0]}</summary>${v[1].map(([c,n])=>`<div class="pair"><span>${c}</span><strong>${n}</strong></div>`).join('')}</details>`).join('')}</section></div><div class="card"><h2>示例地区树与编码纠错</h2><p>云南省 YN → 示例市甲 YN-C01 → 示例县甲 YN-C01-K01；示例市乙 YN-C02 → 示例县乙 YN-C02-K01。</p><p class="muted">应用内代码用于演示。已关联企业的节点不能物理删除，历史快照保持代码与名称。</p>${table(['企业','编码类型','当前编码','操作'],Object.values(S.firms).map(f=>tr([esc(f.profile.name),f.profile.codeType,esc(f.profile.enterpriseCode),btn('管理纠错','code-correct','small',false,f.id)])))}</div><div class="card"><h2>减少类型与原因</h2><div class="grid two"><div>${rt.map(x=>`<p><code>${x.code}</code> ${x.name}</p>`).join('')}</div><div>${rc.map(x=>`<p><code>${x.code}</code> ${x.name}</p>`).join('')}</div></div></div>`}
function monitorPage(){return header('monitor',btn(S.monitorFailed?'恢复采集演示':'采集失败演示','monitor-fail'))+`<div class="callout">节点数据为原型样例，刷新间隔方向为60秒；实际采集及告警需在正式实现中接入。</div>`+summary([['CPU占用',S.monitorFailed?'不可用':'23.4%','','示例应用节点'],['内存使用',S.monitorFailed?'不可用':'3.2 / 8','GB','示例应用节点'],['磁盘使用',S.monitorFailed?'不可用':'28 / 100','GB','示例应用节点'],['交换队列',S.batches.filter(b=>b.status==='QUEUED').length,'个','当前模拟任务']])+`<div class="card">${table(['节点','服务状态','采集时间','数据库连接','错误率'],[tr(['app-demo',S.monitorFailed?'<span class="tag red">采集失败</span>':'<span class="tag green">正常 · 示例</span>',S.monitorFailed?'不可用':S.now,S.monitorFailed?'不可用':'5 / 20',S.monitorFailed?'不可用':'0.00%'])])}</div>`}
function auditPage(){return header('audit')+`<div class="callout">本页记录当前演示中的关键动作。刷新后演示数据重置；正式审计的数据库事务与不可篡改保护不属于原型实现。</div><div class="card">${S.logs.length?table(['事件','时间 / 操作者','操作','对象','变化 / 理由'],S.logs.map(l=>tr([esc(l.id),esc(l.at)+'<br>'+esc(l.who),esc(l.action),esc(l.obj),esc([l.before&&l.before+' → '+l.after,l.reason].filter(Boolean).join('；'))]))):empty('暂无本轮操作事件','提交、审核、修订、导出预览等动作会产生演示记录。')}</div>`}
function trashPage(){const rows=Object.values(S.reports).filter(r=>r&&r.status==='APPROVED');return header('trash')+`<div class="callout warning">删除前查看统计和批次影响，填写理由并二次确认。发送中及结果未知的批次引用禁止删除；已完成批次快照保留。30日内可恢复，不自动报送。</div><div class="card">${table(['企业','月份','状态','删除时间','操作'],rows.map(r=>tr([esc(r.profile.name),r.period,badge(r.deleted?'DELETED':r.status),r.deletedAt||'—',r.deleted?btn('恢复原审核状态','report-restore','small',false,r.id):btn('预览删除影响','report-delete-preview','danger small',false,r.id)])))}</div>`}
function loginPage(){return header('login')+`<div class="card login-panel"><h2>欢迎登录</h2><p class="muted">这里演示界面反馈，不校验真实账号。</p><div id="form-errors" class="errors" role="alert"></div><div class="form-grid">${field('账号','demo-login','qy_a','text','管理员创建，不提供企业自助注册',true,false,true)}${field('密码','demo-password','','password','生产要求12至64字符；原型不保存密码',true,false,true)}</div><div class="form-actions">${btn('模拟密码错误','login-error')}${btn('进入企业演示','login-enter','primary')}</div><hr><small>拟定反馈：5次失败锁15分钟；初登改密；闲置30分钟、绝对8小时失效；管理员另验TOTP。</small></div>`}

const charLen=v=>[...String(v||'')].length;
function validateProfile(p,submit){const errors=[],limits={name:[1,200,'企业名称'],business:[1,500,'经营业务'],contactName:[1,50,'联系人'],addressDetail:[1,200,'详细地址']};for(const [k,[min,max,n]]of Object.entries(limits)){if((submit||p[k])&&(charLen(p[k])<min||charLen(p[k])>max))errors.push(n+'须为'+min+'至'+max+'字。')}
 if(submit&&(!p.natureCode||!p.industryCode))errors.push('必须选择合法两级性质与行业。');
 if(p.natureCode&&!nature[p.natureParent]?.[1].some(x=>x[0]===p.natureCode))errors.push('性质父子关系不匹配。');if(p.industryCode&&!industry[p.industryParent]?.[1].some(x=>x[0]===p.industryCode))errors.push('行业父子关系不匹配。');
 if(S.dictDisabled.includes(p.natureCode))errors.push('所选性质已停用，请选择有效分类。');
 if((submit||p.postalCode)&&!/^\d{6}$/.test(p.postalCode))errors.push('邮编必须为6位数字。');
 const fixed=/^0\d{2,3}-?\d{7,8}$/;if((submit||p.phone)&&!(/^1[3-9]\d{9}$/.test(p.phone)||fixed.test(p.phone)))errors.push('电话必须是国内手机号或带区号的固定电话。');if((submit||p.fax)&&p.fax!=='无'&&!fixed.test(p.fax))errors.push('传真须为固定电话；无传真填“无”。');
 if(p.email&&(charLen(p.email)>254||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(p.email)))errors.push('邮箱格式不正确。');if(p.addressCounty!==p.addressCity+'-K01')errors.push('地址市县父子关系不正确。');return errors}
function formValues(selector){return Object.fromEntries([...new FormData($(selector)).entries()].map(([k,v])=>[k,String(v).trim()]))}
function reportData(selector,r){const x=formValues(selector);return {...r,...x,B:x.B!==undefined?(x.B===''?'':Number(x.B)):r.B,E:x.E!==undefined?(x.E===''?'':Number(x.E)):r.E}}
function validateReport(r,submit=true){const e=[];for(const k of ['B','E']){if(r[k]===''||r[k]===undefined){if(submit)e.push(k+'人数必填。')}else if(!Number.isInteger(Number(r[k]))||r[k]<0||r[k]>2147483647)e.push(k+'必须为0至2,147,483,647的整数。')}
 if(!submit)return e;
 if(charLen(r.otherReason)<1||charLen(r.otherReason)>500)e.push('其他原因须为1至500字，没有情况填“无”。');
 if(r.E<r.B&&!r.reductionType)e.push('人数减少，必须选择减少类型。');if(r.E<r.B&&!r.primaryReason)e.push('人数减少，必须选择主要原因。');
 const selected=[];for(const name of ['primary','secondary','tertiary']){const a=r[name+'Reason']||'',b=r[name+'Description']||'';if(a){selected.push(a);if(!rc.some(x=>x.code===a))e.push('请选择有效原因代码。');if(charLen(b)<1||charLen(b)>500)e.push(({primary:'主要',secondary:'次要',tertiary:'第三'}[name])+'原因说明须为1至500字。')}else if(b)e.push('原因和说明必须成对填写。')}
 if(r.secondaryReason&&!r.primaryReason)e.push('次要原因必须先填写主要原因。');if(r.tertiaryReason&&(!r.primaryReason||!r.secondaryReason))e.push('第三原因必须先填写主要、次要原因。');if(new Set(selected).size!==selected.length)e.push('原因不能在多个序位重复。');return e}
function requireRole(role){if(S.role!==role&&!(role==='admin'&&S.role==='province')){toast('当前演示角色没有此操作权限');return false}return true}
function saveProfile(submit){if(!requireRole('enterprise'))return;activeId='A';const f=firm();if(f.filing==='PENDING'||f.change?.status==='PENDING')return toast('待审资料不可覆盖');const values=formValues('#profile-form'),p={...f.draft,...values};const e=validateProfile(p,submit);if(e.length)return errorMessages(e);f.draft=p;dirty=false;if(submit){if(f.filing==='APPROVED'){f.change={status:'PENDING',data:copy(p)};log('提交资料变更','企业甲')}else{f.filing='PENDING';log('提交备案','企业甲')}profileEditing=false;shell();toast('资料已提交，等待省级备案审核')}else toast('资料草稿已保存，重新进入页面可恢复')}
function saveReport(submit){if(!requireRole('enterprise'))return;activeId='A';let r=rep()||newReport('A',80);if(!canEdit(r))return toast('当前窗口或报表状态不允许修改');const data=reportData('#report-form',r),e=validateReport(data,submit);if(e.length)return errorMessages(e);Object.assign(r,data);S.reports.A=r;dirty=false;if(submit){r.submissionVersion++;r.version++;r.status='CITY_PENDING';r.profile=copy(S.firms.A.profile);r.profileVersion=S.firms.A.profileVersion;r.submittedAt=S.now;r.returnReason='';r.snapshots.push(snapshot(r));S.firms.A.baselineLocked=true;S.firms.A.baseline=r.B;event(r,'企业正式提交');log('月报提交','企业甲 / 2026-09','','草稿或退回','CITY_PENDING');shell();toast('提交成功，已进入市级待审；本次数据已冻结')}else{r.version++;toast('草稿已保存；尚未进入审核和统计')}}
function openFiling(id){activeId=id;const f=firm(),p=f.change?.data||f.draft;modal('备案资料审核',`<div class="callout">${f.change?'资料变更申请；旧资料继续有效':'首次备案申请'} · ${esc(p.name)}</div>${f.change?table(['字段','当前资料','拟变更资料'],Object.keys(p).filter(k=>p[k]!==f.profile[k]).map(k=>tr([esc(k),esc(f.profile[k]),esc(p[k])]))):''}${profileForm(p,true)}<div id="modal-errors" class="errors" role="alert"></div>${area('退回理由','return-reason','','退回时必填，1至500字')}`,btn('退回企业','filing-return','danger')+btn('通过备案','filing-approve','primary'))}
function filingDecision(approve){if(!requireRole('province'))return;const f=firm();if(f.filing!=='PENDING'&&f.change?.status!=='PENDING')return toast('该申请状态已变化');const reason=$('#return-reason').value.trim();if(!approve&&(charLen(reason)<1||charLen(reason)>500))return errorMessages(['退回理由须为1至500字。']);if(approve){f.profile=copy(f.change?.data||f.draft);if(f.change){f.profileVersion++;f.change=null}else f.filing='APPROVED';log('备案通过',f.profile.name)}else{if(f.change)f.change.status='RETURNED';else f.filing='RETURNED';f.filingReason=reason;log('备案退回',f.profile.name,reason)}close();shell();toast(approve?'备案通过，企业可以填报':'已直接退回企业，理由已记录')}
function openReview(id){activeId=id;const r=rep(),target=S.role==='city'?'CITY_PENDING':'PROVINCE_PENDING';if(!r||r.status!==target||S.role==='city'&&r.profile.cityCode!=='YN-C01')return toast('此记录不在当前待审范围');modal('单条月报审核',reportDetail(r,true)+`<div id="modal-errors" class="errors" role="alert"></div>${area('退回理由','return-reason','','月报退回备注选填，最多500字')}`,btn('退回企业','review-return','danger')+btn('通过本级审核','review-approve','primary'))}
function reviewDecision(approve){const r=rep();if(!['city','province'].includes(S.role))return toast('无审核权限');const expected=S.role==='city'?'CITY_PENDING':'PROVINCE_PENDING';if(r.status!==expected)return toast('版本状态已变化，需重新读取');const reason=$('#return-reason').value.trim();if(!approve&&(charLen(reason)>500))return errorMessages(['退回备注最多500字。']);const before=r.status;r.status=approve?(S.role==='city'?'PROVINCE_PENDING':'APPROVED'):(S.role==='city'?'CITY_RETURNED':'PROVINCE_RETURNED');r.version++;r.returnReason=approve?'':reason;if(r.status==='APPROVED')r.approvedAt=new Date(S.now.replace(' ','T')+'+08:00').toISOString().replace('.000','');event(r,roles[S.role]+(approve?'通过':'退回'),reason);log('月报审核',r.profile.name,reason,before,r.status);close();shell();toast(approve?(S.role==='city'?'通过成功，已自动进入省级待审':'省审通过，已纳入统计与报送'):'已退回企业；重提后重新走两级审核')}
function openCorrection(id){activeId=id;const r=rep();if(!['PROVINCE_PENDING','APPROVED'].includes(r.status)||r.deleted)return toast('待省审或省审通过的报表可另存修订');const d=r.revisionDraft?.data||{...r,E:id==='A'?85:55};modal('另存独立修订',`<div class="callout">${esc(r.profile.name)} · 原始B${r.B} / E${r.E}。保存不生效，原始数据及批次不被覆盖。</div><form id="correction-form"><div id="modal-errors" class="errors" role="alert"></div><div class="form-grid">${field('修订建档人数 B','B',d.B,'number','历史错误在本月修订，不反向改基准',true)}${field('修订调查人数 E','E',d.E,'number','示例甲由80改为85',true)}${selectField('减少类型','reductionType',rt,d.reductionType)}${selectField('主要原因','primaryReason',rc,d.primaryReason)}${area('主要说明','primaryDescription',d.primaryDescription,'仅人数减少时必填')}${area('其他原因','otherReason',d.otherReason,'无情况填“无”',true)}${area('修订理由','correction-reason',r.revisionDraft?.reason||'示例核对后更正就业人数','必填1至500字',true)}</div></form>`,btn('保存未生效修订','correction-save','primary'))}
function saveCorrection(){if(!requireRole('province'))return;const r=rep(),data=reportData('#correction-form',r),reason=$('#correction-reason').value.trim(),e=validateReport(data);if(!reason||charLen(reason)>500)e.push('修订理由须为1至500字。');if(e.length)return errorMessages(e);const clean={};for(const k of ['B','E','otherReason','reductionType','primaryReason','primaryDescription','secondaryReason','secondaryDescription','tertiaryReason','tertiaryDescription'])clean[k]=data[k];r.revisionDraft={data:clean,reason,version:Math.max(r.revision?.version||0,...(r.revisionHistory||[]).map(v=>v.version))+1,active:false};log('另存修订',r.profile.name,reason,`E${r.E}`,`E${data.E} · 未生效`);close();shell();toast('修订已保存但未生效；请核对后点击“生效”')}
function correctionToggle(id,active){if(!requireRole('province'))return;const r=S.reports[id];r.revisionHistory ||= [];let changed;if(active){r.revision=copy(r.revisionDraft);r.revision.active=true;r.revisionHistory.push(r.revision);r.revisionDraft=null;changed=r.revision}else{changed=r.revision;changed.active=false;r.revision=[...r.revisionHistory].reverse().find(v=>v.active)||changed}event(r,active?'修订生效':'修订撤销',changed.reason);log(active?'修订生效':'撤销修订',r.profile.name,changed.reason);close();shell();toast(active?'修订已生效，修订口径随之变化；原始及批次不变':'已撤销本次生效，恢复上一有效修订或原始值')}
function supplementNew(){modal('新增补报授权',`<div id="modal-errors" class="errors" role="alert"></div><form id="supplement-form"><div class="form-grid">${selectField('企业','supplement-id',[['A','示例企业甲'],['B','示例企业乙']],'A','仅草稿或退回可授权',true)}${field('调查月份','supplement-period','2026-09','month','本原型固定展示9月',true,true)}${field('授权小时数','supplement-hours',72,'number','默认72小时，最多168小时',true)}${area('授权理由','supplement-reason','示例企业需要补报','必填1至500字',true)}</div></form>`,btn('授予补报窗口','supplement-save','primary'))}
function supplementSave(){if(!requireRole('province'))return;const id=$('#supplement-id').value,h=Number($('#supplement-hours').value),reason=$('#supplement-reason').value.trim(),r=S.reports[id];if(!['A','B'].includes(id)||!Number.isInteger(h)||h<1||h>168||!reason||charLen(reason)>500)return errorMessages(['小时数须为1至168的整数，理由须为1至500字。']);if(r&&(!['DRAFT','CITY_RETURNED','PROVINCE_RETURNED'].includes(r.status)||r.deleted))return errorMessages(['待审、已通过、已删除报表不能用补报授权解锁。']);const start=new Date(S.now.replace(' ','T')+'+08:00'),end=new Date(start.getTime()+h*3600000);const stamp=new Date(end.getTime()+8*3600000).toISOString().slice(0,16).replace('T',' ');S.supplements.push({key:uid(),id,period:'2026-09',start:S.now,end:stamp,reason});log('补报授权',S.firms[id].profile.name,reason,'无授权',h+'小时');close();shell();toast('补报授权已建立；切回企业后可保存并提交')}
function recordPayload(raw){const r=effective(raw),f=S.firms[r.id],rev=basis==='CORRECTED'&&raw.revision?.active?raw.revision.version:0;return{recordKey:[f.uuid,r.period,r.submissionVersion,rev].join(':'),enterpriseId:f.uuid,profileVersion:r.profileVersion,submissionVersion:r.submissionVersion,revisionVersion:rev,codeType:r.profile.codeType,enterpriseCode:r.profile.enterpriseCode,enterpriseName:r.profile.name,cityCode:r.profile.cityCode,countyCode:r.profile.countyCode,zoneCode:r.profile.zoneCode,natureCode:r.profile.natureCode,industryCode:r.profile.industryCode,baselineCount:r.B,employedCount:r.E,otherReason:r.otherReason,reductionType:r.reductionType||null,primaryReason:r.primaryReason||null,primaryDescription:r.primaryDescription||null,secondaryReason:r.secondaryReason||null,secondaryDescription:r.secondaryDescription||null,tertiaryReason:r.tertiaryReason||null,tertiaryDescription:r.tertiaryDescription||null,approvedAt:raw.approvedAt}}
async function createBatch(rows=validReports(),parent=null){if(!requireRole('province'))return;if(!rows.length)return toast('没有有效省审报表');const mode=$('#exchange-mode')?.value||'MOCK',scene=$('#mock-receipt')?.value||'success',id=uid(),records=rows.map(recordPayload).sort((a,b)=>a.recordKey.localeCompare(b.recordKey));const payload={schemaVersion:1,batchId:id,provinceCode:'YN',period:'2026-09',mode,dataBasis:basis,formulaVersion:1,createdAt:new Date(S.now.replace(' ','T')+'+08:00').toISOString().replace('.000',''),recordCount:records.length,records};if(parent)payload.supersedesBatchId=parent.id;let hash='原型环境不支持摘要计算';if(globalThis.crypto?.subtle){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(payload)));hash=[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('')}
 const b={id,label:(mode==='MOCK'?'模拟':'真实')+'-20261006-'+String(S.batches.length+1).padStart(3,'0'),mode,basis,scene,period:'2026-09',records:copy(records),payload:{...payload,payloadHash:hash},status:'QUEUED',receipt:null,supersedes:parent?.id};S.batches.unshift(b);log('创建冻结批次',b.label,'口径'+basis);shell();toast('批次已冻结，后续数据修订不会改写载荷')}
function batchDetail(id){const b=S.batches.find(x=>x.id===id);modal('冻结批次与接收回执',`<div class="callout">${esc(b.label)} · ${b.mode} · ${b.basis} ${badge(b.status)}</div>${pair('批次UUID','<code>'+esc(b.id)+'</code>')}${pair('载荷摘要','<code>'+esc(b.payload.payloadHash)+'</code>')}${pair('冻结总人数',b.records.reduce((a,r)=>a+r.employedCount,0)+' 人')}${pair('接收凭证',esc(b.receipt?.receiptId||'尚无接收回执'))}${table(['企业','原始提交 / 修订','B / E','接收结果'],b.records.map(r=>tr([esc(r.enterpriseName),'v'+r.submissionVersion+' / v'+r.revisionVersion,r.baselineCount+' / '+r.employedCount,esc(b.receipt?.items.find(i=>i.recordKey===r.recordKey)?.result||'待回执')])))}<details><summary>查看规范化载荷（不含联系方式）</summary><pre class="pre">${esc(JSON.stringify(b.payload,null,2))}</pre></details>${b.receipt?`<details><summary>逐条回执</summary><pre class="pre">${esc(JSON.stringify(b.receipt,null,2))}</pre></details>`:''}`)}
function acceptReceipt(b,partial=false){const items=b.records.map((r,i)=>({recordKey:r.recordKey,result:partial&&i===0?'REJECTED':'ACCEPTED',errorCode:partial&&i===0?'MOCK_FIELD_REJECTED':null,message:partial&&i===0?'示例接收端要求核对就业人数':null}));b.receipt={batchId:b.id,receiptId:'MOCK-RCPT-'+uid().slice(0,8),receivedAt:S.now,acceptedCount:items.filter(x=>x.result==='ACCEPTED').length,rejectedCount:items.filter(x=>x.result==='REJECTED').length,items};b.status=partial?'REJECTED':'ACKNOWLEDGED';log('模拟回执',b.label,'接受'+b.receipt.acceptedCount+'，拒绝'+b.receipt.rejectedCount)}
async function sendBatch(id){if(!requireRole('province'))return;const b=S.batches.find(x=>x.id===id);if(b.mode==='REAL')return modal('真实接入未配置','<div class="errors">EXCHANGE_NOT_CONFIGURED</div><p>没有真实URL、认证凭据、编码映射及协议适配；此处不会切换为模拟发送。</p>');if(b.status!=='QUEUED')return toast('当前状态不能再次盲目发送');b.status='SENDING';shell();await new Promise(resolve=>setTimeout(resolve,450));if(b.scene==='unknown')b.status='UNKNOWN';else if(b.scene==='unauthorized'){b.status='REJECTED';b.authError=true;log('模拟认证失败',b.label,'401，不自动重试')}else acceptReceipt(b,b.scene==='partial');shell();toast(b.status==='UNKNOWN'?'响应超时，结果未知；请先查回执':b.authError?'模拟401认证失败，不自动重试':b.status==='ACKNOWLEDGED'?'模拟接收成功；不是实际国家接收':'部分拒绝；已接受项保留，失败项需修正后补发')}
function batchRetry(id){const b=S.batches.find(x=>x.id===id);if(b.authError)return modal('模拟认证失败','<p>认证失败不能按数据失败项补发。请核查认证配置；正式系统禁止自动重试401/403。</p>');const failed=b.receipt?.items.filter(x=>x.result==='REJECTED')||[],ids=failed.map(x=>b.records.find(r=>r.recordKey===x.recordKey).enterpriseId),rows=validReports().filter(r=>ids.includes(S.firms[r.id].uuid));basis='CORRECTED';if(rows.some(r=>failed.some(x=>x.recordKey===recordPayload(r).recordKey)))return modal('先修正失败条目','<p>失败项仍为旧提交／修订版本。请另存修订并生效，再使用修订口径补发；已接受条目不会重发。</p>',btn('去独立数据修订','to-correction','primary'));createBatch(rows,b)}

const exportColumns={firms:['企业ID','编码类型','企业编码','名称','市','县','区域','性质','行业','经营业务','联系人','地址','邮编','电话','传真','邮箱','备案状态','资料版本'],reports:['企业ID','编码类型','企业编码','名称','市','县','区域','性质','行业','月份','B','E','E减B','max(B减E与0)','减少类型','主要原因','主要说明','次要原因','次要说明','第三原因','第三说明','其他原因','审核状态','提交时间','口径','提交版本','修订版本'],accounts:['用户ID','账号','用户类型','角色','市','县','区域','企业ID','名称','启停状态','创建时间']};
function exportPreview(){if(!['province','admin'].includes(S.role)||S.role==='admin'&&!S.accountExport)return toast('当前角色无导出授权');const kind=route==='users'?'accounts':route==='archives'?'firms':'reports',cols=exportColumns[kind],count=kind==='accounts'?S.users.filter(u=>!u.deleted).length:kind==='firms'?Object.keys(S.firms).length:route==='query'?(S.queryCount??Object.values(S.reports).filter(r=>r&&!r.deleted&&r.profile.name.includes(queryText)).length):validReports().length;log('导出预览',meta[route][0],'原型预览，不生成业务XLSX');modal('XLSX导出预览',`<div class="callout">本原型展示文件结构与交互反馈，不生成业务XLSX。正式实现需导出全部命中行，而非当前页。</div>${pair('预计记录数',count+' 条')}${pair('工作表','数据 + 查询说明')}${pair('数据口径',basis==='ORIGINAL'?'原始有效口径':'修订有效口径')}${pair('下载方向','生成后24小时有效，下载再次鉴权')}${pair('异步方向','超过10,000行显示任务进度及结果')}<h3 class="section-gap">数据表固定列顺序</h3><p>${cols.map((c,i)=>`<span class="tag gray" style="margin:4px">${i+1}. ${c}</span>`).join('')}</p><h3>查询说明表</h3><p>筛选、生成者、时间、口径、公式版本1、记录数、字段版本。编码与电话为文本，人数为整数，公式开头文本不执行公式。</p>`)}
function showHelp(){const rule=reviewRules[route]||[meta[route][1]],note=notes.find(n=>n.page===route);modal('页面评审说明',`<div class="pill-row"><span class="tag">${meta[route][0]}</span><span class="tag gray">${meta[route][2]}</span></div><h3>本页要确认的方向</h3>${rule.map(x=>'<p>• '+esc(x)+'</p>').join('')}<hr><div class="field"><label for="review-direction">界面方向记录</label><select id="review-direction"><option value="沿用当前方向" ${note?.direction==='沿用当前方向'?'selected':''}>沿用当前方向</option><option value="建议调整" ${note?.direction==='建议调整'?'selected':''}>建议调整</option></select></div><div class="field section-gap"><label for="review-note">具体记录</label><textarea id="review-note" placeholder="例如：主要原因说明应直接放在原因选择下方">${esc(note?.text||'')}</textarea><small>记录仅保存到此浏览器，不发送给任何人。浏览器禁止本地存储时，可在本次会话中导出。</small></div>`,btn('查看全部方向记录','notes-view')+btn('保存本页方向','note-save','primary'))}
function showNotes(){modal('需求方向记录',`${notes.length?table(['页面','对应需求','方向','具体记录'],notes.map(n=>tr([esc(meta[n.page]?.[0]||n.page),esc(meta[n.page]?.[2]||''),esc(n.direction),esc(n.text||'无补充')]))):empty('尚无方向记录','从任意页面的“页面评审说明”中记录。')}<p class="muted section-gap">导出为Markdown，可附在需求评审记录中；不会自动发送或产生跨部门审批。</p>`,btn('导出方向记录','notes-export','primary',!notes.length))}
function saveNote(){const n={page:route,direction:$('#review-direction').value,text:$('#review-note').value.trim(),at:new Date().toISOString()},i=notes.findIndex(v=>v.page===route);if(i<0)notes.push(n);else notes[i]=n;try{localStorage.setItem('yn-prototype-review-notes',JSON.stringify(notes))}catch{}close();toast('本页界面方向已记入本地记录')}
function downloadNotes(){const text='# 云南企业就业监测 · 原型方向记录\n\n基于SRS V1.2暂定实施稿，界面主体V1.1；新增正式规则尚未实现，记录仅表示界面讨论结果。\n\n'+notes.map(n=>'## '+meta[n.page][0]+'\n\n- 需求：'+meta[n.page][2]+'\n- 方向：'+n.direction+'\n- 时间：'+n.at+'\n\n'+(n.text||'无补充')+'\n').join('\n');const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.href=url;a.download='原型需求方向记录.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function userNew(){modal('创建示例账号',`<div id="modal-errors" class="errors" role="alert"></div><form id="user-form"><div class="form-grid">${field('账号','user-login','','text','3至64位字母数字下划线短横线，忽略大小写唯一',true)}${selectField('业务身份','user-type',[['企业','企业'],['市级','市级'],['省级','省级']],'企业','身份决定角色边界',true)}${selectField('企业归属','user-firm',[['A','示例企业甲'],['B','示例企业乙']],'A','企业身份仅关联单一企业')}${selectField('所属市','user-city',[['YN-C01','示例市甲'],['YN-C02','示例市乙']],'YN-C01','市级身份仅关联单一市')}</div></form><p class="muted section-gap">正式实现生成随机初始口令、首登强制修改；原型不创建真实凭据。</p>`,btn('创建示例账号','user-save','primary'))}
function userSave(){if(!requireRole('admin'))return;const login=$('#user-login').value.trim(),type=$('#user-type').value;if(!['企业','市级','省级'].includes(type)||(type==='企业'&&!['A','B'].includes($('#user-firm').value))||(type==='市级'&&!['YN-C01','YN-C02'].includes($('#user-city').value))||!/^[A-Za-z0-9_-]{3,64}$/.test(login)||S.users.some(u=>u.login.toLowerCase()===login.toLowerCase()))return errorMessages(['账号格式非法或忽略大小写后重复。']);const map={'企业':'企业','市级':'市级审核','省级':'省级业务'};S.users.push({id:uid(),login,type,firm:type==='企业'?$('#user-firm').value:null,city:type==='市级'?$('#user-city').value:null,roles:[map[type]],enabled:true});log('创建账号',login,'随机初始口令在正式实现中生成');close();shell();toast('示例账号已创建；未产生真实登录凭据')}
function openUserRoles(id){activeId=id;const u=S.users.find(v=>v.id===id);modal('账号角色授权',`<p><strong>${esc(u.login)}</strong> · ${u.type}</p><div id="modal-errors" class="errors" role="alert"></div><div class="checks">${['企业','市级审核','省级业务','系统管理'].map(r=>`<label><input type="checkbox" name="user-role-check" value="${r}" ${u.roles.includes(r)?'checked':''}>${r}</label>`).join('')}</div><p class="muted section-gap">企业、市级、省级业务身份互斥；系统管理仅授予独立管理或省级账号。移除后下一请求生效。</p>`,btn('保存角色并立即生效','user-role-save','primary'))}
function userRolesSave(){const u=S.users.find(v=>v.id===activeId),chosen=[...document.querySelectorAll('input[name="user-role-check"]:checked')].map(v=>v.value),business=chosen.filter(v=>v!=='系统管理'),own={'企业':'企业','市级':'市级审核','省级':'省级业务','系统管理':null}[u.type];if(business.length>1||business.some(v=>v!==own)||chosen.includes('系统管理')&&!['省级','系统管理'].includes(u.type))return errorMessages(['业务身份互斥，不能跨身份授权；管理权限仅用于省级或独立管理账号。']);u.roles=chosen;log('变更角色',u.login,chosen.join('、')||'无角色，停止业务');close();shell();toast('角色已保存；无角色账号停止业务访问')}
function openNotice(id){const n=S.notices.find(v=>v.id===id)||{title:'',body:''};activeId=id||'';modal(id?'修改本人通知':'发布省级通知',`<form id="notice-form"><div id="modal-errors" class="errors" role="alert"></div><div class="form-grid">${field('标题','notice-title',n.title,'text','1至50字',true,false,true)}${area('通知内容','notice-body',n.body,'1至2000字，纯文本，换行算1字',true)}</div></form><p class="muted">单位固定省级，首次发布时间自动生成；修改另记更新时间。</p>`,btn(id?'保存修改':'发布通知','notice-save','primary'))}
function saveNotice(){if(!requireRole('province'))return;const title=$('#notice-title').value.trim(),body=$('#notice-body').value.trim();if(!title||charLen(title)>50||!body||charLen(body)>2000)return errorMessages(['标题须为1至50字，内容须为1至2000字；不能纯空白。']);const n=S.notices.find(v=>v.id===activeId);if(n&&n.author!=='省级业务甲')return toast('只能修改本人发布的通知');if(n)Object.assign(n,{title,body,updatedAt:S.now});else S.notices.unshift({id:uid(),title,body,createdAt:S.now,author:'省级业务甲',deleted:false});log(n?'修改通知':'发布通知',title);close();shell();toast('通知已更新，所有业务角色可以阅读')}
function deletePreview(id){const r=S.reports[id],refs=S.batches.filter(b=>b.records.some(x=>x.enterpriseId===S.firms[id].uuid)),blocked=refs.some(b=>['SENDING','UNKNOWN'].includes(b.status));activeId=id;modal('预览历史删除影响',`<div class="callout ${blocked?'warning':''}">${esc(r.profile.name)} · ${r.period}${blocked?'<br>有发送中或结果未知批次引用，禁止删除。':''}</div>${pair('预计删除条数','1条月报及统计入口（保留原始快照和审计）')}${pair('统计影响','原始与修订口径都排除此企业')}${pair('批次引用',refs.length+' 个，完成批次的冻结载荷继续保留')}<div id="modal-errors" class="errors" role="alert"></div>${area('删除理由','delete-reason','','1至500字必填，下一步还需确认')}`,btn('下一步：二次确认','report-delete-confirm','danger',blocked))}
let pendingDeleteReason='';
function codeCorrect(id){activeId=id;const f=firm();modal('管理纠错 · 地区与企业编码',`<form id="code-form"><div id="modal-errors" class="errors" role="alert"></div><div class="form-grid">${selectField('编码类型','codeType',[['ORG9','ORG9组织机构代码'],['USCC18','USCC18统一社会信用代码']],f.profile.codeType,'类型加值唯一',true)}${field('企业编码','enterpriseCode',f.profile.enterpriseCode,'text','首版格式校验，不计算校验位',true)}${selectField('所属市','codeCity',[['YN-C01','示例市甲'],['YN-C02','示例市乙']],f.profile.cityCode,'县跟随所选示例市',true)}${area('纠错理由','code-reason','','必填，历史快照与企业UUID不变',true)}</div></form>`,btn('保存新的资料版本','code-save','primary'))}
function codeSave(){if(!requireRole('admin'))return;const f=firm(),type=$('#codeType').value,raw=$('#enterpriseCode').value.trim().toUpperCase(),code=type==='ORG9'?raw.replace('-',''):raw,reason=$('#code-reason').value.trim(),city=$('#codeCity').value;if(!['YN-C01','YN-C02'].includes(city)||!(type==='ORG9'?/^[A-Z0-9]{9}$/:/^[A-Z0-9]{18}$/).test(code)||!reason||charLen(reason)>500||Object.values(S.firms).some(x=>x.id!==f.id&&x.profile.enterpriseCode===code&&x.profile.codeType===type))return errorMessages(['编码须符合9/18位格式且类型加值唯一；理由1至500字。']);Object.assign(f.profile,{codeType:type,enterpriseCode:code,cityCode:city,countyCode:city+'-K01'});f.profileVersion++;f.draft=copy(f.profile);log('管理编码地区纠错',f.profile.name,reason);close();shell();toast('新资料版本已保存，企业UUID及历史快照保持不变')}
function baselineNew(){modal('企业未来基准规划',`<div id="modal-errors" class="errors" role="alert"></div><div class="form-grid">${selectField('企业','baseline-id',[['A','示例企业甲'],['B','示例企业乙']],'A')}${field('新基准 B','baseline-value',100,'number','0至2,147,483,647',true)}${field('生效月份','baseline-month','2026-10','month','须晚于已提交最大月份2026-09',true)}${area('调整理由','baseline-reason','','只作用之后新报表，不改历史或现有基准快照',true)}</div>`,btn('保存前向基准版本','baseline-save','primary'))}
const actionHandlers={
 close,help:showHelp,'notes-view':showNotes,'note-save':saveNote,'notes-export':downloadNotes,
 'start-journey':()=>{seed('onboarding');journey=0;S.role='province';route='users';shell()},
 'journey-prev':()=>{journey=Math.max(0,journey-1);S.role=journeySteps[journey][1];route=journeySteps[journey][2];shell()},
 'journey-next':()=>{const ready=[true,['PENDING','APPROVED'].includes(S.firms.A.filing),S.firms.A.filing==='APPROVED',S.reports.A&&S.reports.A.status!=='DRAFT',S.reports.A&&['PROVINCE_PENDING','APPROVED'].includes(S.reports.A.status),S.reports.A?.status==='APPROVED',true,true][journey];if(!ready)return toast('请先完成当前步骤的提交或审核，再进入下一步');if(journey===7){journey=-1;route='guide';shell();toast('完整业务导览结束；可继续查看异常场景与页面评审说明')}else{journey++;S.role=journeySteps[journey][1];route=journeySteps[journey][2];shell()}},
 'journey-exit':()=>{journey=-1;shell()},reset:()=>modal('重置本轮演示','<p>企业资料、月报、审核、修订及批次恢复当前场景初始值。已保存的方向记录继续保留。</p>',btn('重置示例业务数据','reset-confirm','danger')),
 'reset-confirm':()=>{const role=S.role;seed(S.scenario);S.role=role;journey=-1;close();shell();toast('业务示例已重置')},
 'login-view':()=>{route='login';shell()},'login-error':()=>errorMessages(['账号或密码错误。拟定规则：5次失败锁15分钟；原型不执行真实认证。']),'login-enter':()=>{S.role='enterprise';route='dashboard';shell();toast('已进入角色演示；真实密码未保存')},
 'go-profile':()=>go('profile'),'profile-edit':()=>{profileEditing=true;S.firms.A.draft=copy(S.firms.A.change?.data||S.firms.A.profile);shell()},'profile-save':()=>saveProfile(false),'profile-submit':()=>saveProfile(true),'profile-preview':()=>modal('已提交资料 · 只读',profileForm(S.firms.A.change?.data||S.firms.A.draft,true)),
 'to-enterprise-profile':()=>{close();S.role='enterprise';route='profile';shell()},'filing-detail':openFiling,'filing-approve':()=>filingDecision(true),'filing-return':()=>filingDecision(false),
 'report-save':()=>saveReport(false),'report-submit':()=>saveReport(true),'review-detail':openReview,'review-approve':()=>reviewDecision(true),'review-return':()=>reviewDecision(false),
 'report-detail':id=>modal('历史与提交版本 · 只读',reportDetail(S.reports[id])),
 'archive-detail':id=>{const f=S.firms[id],p=$('#archive-basis')?.selectedIndex===1&&S.reports[id]?.submissionVersion?S.reports[id].profile:f.profile;modal('已备案企业 · 只读档案',profileForm(p,true))},
 'archive-search':()=>{const text=$('#archive-search').value.trim();document.querySelectorAll('.data tbody tr').forEach(row=>row.hidden=!row.textContent.includes(text));toast('已按名称查询；详情资料范围使用当前选择')},
 'query-reports':()=>{queryTab='reports';shell()},'query-accounts':()=>{queryTab='accounts';shell()},'query-clear':()=>{queryText='';S.queryCount=undefined;shell()},
 'query-search':()=>{const start=$('#query-start').value,end=$('#query-end').value,state=$('#query-state').value,month=$('#query-month').value;if(start&&end&&start>end)return errorMessages(['开始日期不能晚于结束日期。']);queryText=$('#query-name').value.trim();const rows=Object.values(S.reports).filter(r=>r&&!r.deleted&&r.profile.name.includes(queryText)&&(!state||r.status===state)&&(!month||r.period===month)&&(!start||r.submittedAt&&r.submittedAt.slice(0,10)>=start)&&(!end||r.submittedAt&&r.submittedAt.slice(0,10)<=end));$('#query-results').innerHTML=rows.length?table(['企业','所属市','月份','B / E','状态','提交版本','操作'],reportRows(rows)):empty('无命中记录','调整交集筛选条件后重试。');$('#query-total').textContent='共 '+rows.length+' 条 · 条件取交集';$('#form-errors').innerHTML='';S.queryCount=rows.length},
 'export-preview':exportPreview,'go-correction':()=>go('correction'),'to-correction':()=>{close();route='correction';shell()},'correction-edit':openCorrection,'correction-save':saveCorrection,
 'correction-activate':id=>{activeId=id;modal('确认修订生效',`<p>本次修订影响修订口径；原始数据及已有批次不变。理由：${esc(S.reports[id].revisionDraft.reason)}</p>`,btn('确认生效','correction-activate-confirm','primary'))},'correction-activate-confirm':()=>correctionToggle(activeId,true),
 'correction-revoke':id=>{activeId=id;modal('撤销修订生效','<p>撤销后恢复上一有效修订或原始取值，历史修订版本仍保留。</p>',btn('确认撤销生效','correction-revoke-confirm','danger'))},'correction-revoke-confirm':()=>correctionToggle(activeId,false),
 'supplement-new':supplementNew,'supplement-save':supplementSave,'supplement-expire':id=>{const x=S.supplements.find(x=>x.key===id);x.end=S.now;log('补报授权到期演示',S.firms[x.id].profile.name);shell();toast('已使补报授权到期，不能再提交')},
 'batch-create':()=>createBatch(),'batch-detail':batchDetail,'batch-send':sendBatch,'batch-retry':batchRetry,'batch-receipt':id=>{const b=S.batches.find(x=>x.id===id);acceptReceipt(b);shell();toast('模拟查询得到回执；已确认模拟接收成功，没有重发')},
 'notice-new':()=>openNotice(''),'notice-edit':openNotice,'notice-save':saveNotice,'notice-delete':id=>{activeId=id;modal('删除本人通知','<p>逻辑删除后，普通列表与详情均不可读。</p>',btn('确认删除通知','notice-delete-confirm','danger'))},'notice-delete-confirm':()=>{const n=S.notices.find(x=>x.id===activeId);if(n.author!=='省级业务甲')return toast('只可删除本人通知');n.deleted=true;log('删除通知',n.title);close();shell()},
 'user-new':userNew,'user-save':userSave,'user-role':openUserRoles,'user-role-save':userRolesSave,'user-toggle':id=>{const u=S.users.find(x=>x.id===id);u.enabled=!u.enabled;log(u.enabled?'启用账号':'停用账号',u.login);shell();toast(u.enabled?'账号已启用':'账号已停用；正式实现应立即失效现有会话')},
 'user-delete':id=>{const u=S.users.find(x=>x.id===id);if(u.firm&&S.reports[u.firm]?.submissionVersion)return modal('有提交数据，禁止删除','<p>此账号关联企业已有提交记录；请使用“停用”，保留业务和审计关联。</p>');activeId=id;modal('逻辑删除账号',`<p>确认删除 ${esc(u.login)}？审计标识将保留。</p>`,btn('确认删除账号','user-delete-confirm','danger'))},'user-delete-confirm':()=>{S.users.find(u=>u.id===activeId).deleted=true;log('逻辑删除账号',activeId);close();shell()},
 'role-new':()=>modal('新增角色模板的界面方向','<p>角色名称、功能勾选、数据范围与关联用户形成模板。首版身份边界不能被自定义模板扩大。</p><p>这个次要管理操作采用说明稿表达；四种身份的可点击主流程已提供。</p>'),
 'role-delete':()=>modal('删除已分配角色 · 二次确认','<p>删除演示只读角色模板，影响0名用户。正式已分配角色必须列影响数量并解除关联，用户及历史保留。</p>',btn('确认删除模板','role-delete-confirm','danger')),'role-delete-confirm':()=>{S.customRole=false;log('删除角色模板','示例只读角色','解除关联，保留用户');close();shell()},
 'period-save':()=>{const start=$('#periodStart').value,end=$('#periodEnd').value;if(!start||!end||start>=end)return errorMessages(['开始时间必须早于截止时间。']);S.periodStart=start;S.periodEnd=end;const now=S.now.replace(' ','T');S.open=now>=start&&now<end;dirty=false;log('修改调查窗口','2026-09',start+' 至 '+end);shell();toast('窗口配置已保存，截止时刻不包含，旧提交不变')},
 'dict-disable':id=>{S.dictDisabled.push(id);log('停用字典',id,'历史代码名称保留');shell();toast('分类已停用，新资料不能再选；历史继续显示')},
 'dict-import':()=>modal('UTF-8 JSON配置导入预览',`<div class="callout">用于地区和字典，不用于月报批量导入。本页展示输入结构和校验方向，不替换正式地区配置。</div>${area('配置JSON','dict-json',JSON.stringify([{code:'YN',name:'云南省',parentCode:null,level:1,enabled:true},{code:'YN-C01',name:'示例市甲',parentCode:'YN',level:2,enabled:true}],null,2),'代码唯一、父子合法、已引用代码不可删除')}<div id="modal-errors" class="errors" role="alert"></div>`,btn('校验并预览','dict-import-check','primary')),
 'dict-import-check':()=>{try{const a=JSON.parse($('#dict-json').value);if(!Array.isArray(a)||a.some(x=>!x.code||!x.name||!Number.isInteger(x.level))||new Set(a.map(x=>x.code)).size!==a.length)throw Error('格式错误');modal('配置校验预览',`<p>共${a.length}项；可进入父子与引用检查。原型未执行持久化导入。</p><pre class="pre">${esc(JSON.stringify(a,null,2))}</pre>`)}catch{errorMessages(['请输入合法JSON数组，代码、名称、层级必填，代码不能重复。'])}},
 'code-correct':codeCorrect,'code-save':codeSave,'baseline-new':baselineNew,'baseline-save':()=>{const id=$('#baseline-id').value,B=Number($('#baseline-value').value),month=$('#baseline-month').value,reason=$('#baseline-reason').value.trim();if(!['A','B'].includes(id)||!Number.isInteger(B)||B<0||B>2147483647||month<='2026-09'||!reason||charLen(reason)>500)return errorMessages(['新B须为非负整数；生效月份晚于2026-09；理由必填1至500字。']);S.firms[id].futureBaseline={B,month,reason};log('新增前向基准',S.firms[id].profile.name,reason,'现有快照不变',month+' B='+B);close();toast('未来基准已规划，已有9月报表B不变')},
 'monitor-fail':()=>{S.monitorFailed=!S.monitorFailed;shell()},
 'report-delete-preview':deletePreview,'report-delete-confirm':()=>{pendingDeleteReason=$('#delete-reason').value.trim();if(!pendingDeleteReason||charLen(pendingDeleteReason)>500)return errorMessages(['删除理由须为1至500字。']);modal('二次确认逻辑删除',`<p>确认将 ${esc(S.firms[activeId].profile.name)} 的2026年9月报表退出统计？已完成报送批次不会被删除。</p><p>理由：${esc(pendingDeleteReason)}</p>`,btn('确认逻辑删除','report-delete-execute','danger'))},
 'report-delete-execute':()=>{const r=rep();if(S.batches.some(b=>['SENDING','UNKNOWN'].includes(b.status)&&b.records.some(x=>x.enterpriseId===S.firms[r.id].uuid)))return toast('发送中或未知结果批次引用，禁止删除');r.deleted=true;r.deletedAt=S.now;log('逻辑删除月报',r.profile.name,pendingDeleteReason);close();shell();toast('月报已退出统计；旧批次仍可复算')},
 'report-restore':id=>{const r=S.reports[id];if(new Date(S.now.replace(' ','T')+'+08:00')-new Date(r.deletedAt.replace(' ','T')+'+08:00')>=30*86400000)return toast('超过30日恢复期');r.deleted=false;r.deletedAt=null;log('恢复月报',r.profile.name,'不自动报送');shell();toast('已恢复原审核状态，未自动建立报送批次')},
 boundaries:()=>modal('原型范围与交付边界',`<h3>可实际点击演示</h3><p>备案、资料变更、填报校验、两级审核退回、72小时补报、修订生效撤销、双口径统计、冻结批次、模拟回执、逻辑删除恢复、通知及用户管理、方向记录导出。</p><h3>采用界面或说明稿表达</h3><p>生产登录与TOTP、任意期别及维度分析、批量配置导入、自定义角色完整编辑、XLSX生成、真实监控、国家协议适配和真实接入。</p><h3>不承担生产能力</h3><p>没有后端、数据库、真实权限隔离、网络发送或性能与安全合规验证。业务示例只在当前页面内存中运行；方向记录可本地保存与导出。</p>`)
};
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{if(b.dataset.go)return go(b.dataset.go);if(b.dataset.leave){dirty=false;close();return go(b.dataset.leave)}if(b.dataset.roleGo){if(dirty)return toast('请先保存当前输入，再切换工作台');S.role=b.dataset.roleGo;route=b.dataset.target;return shell()}if(b.dataset.action){const fn=actionHandlers[b.dataset.action];if(fn)await fn(b.dataset.id);else toast('此操作暂无演示')}}catch(err){console.error(err);toast('原型操作未完成，请重置当前场景后重试')}});
document.addEventListener('submit',e=>e.preventDefault());
document.addEventListener('change',e=>{const t=e.target;switch(t.id){case 'role-switch':if(dirty){toast('请先保存当前输入，再切换角色');t.value=S.role;return}S.role=t.value;route=route==='guide'?'guide':'dashboard';profileEditing=false;activeId='A';shell();break;case 'scenario-switch':if(dirty){toast('请先保存输入或使用重置演示');t.value=S.scenario;return}const role=S.role;seed(t.value);S.role=role;journey=-1;route='dashboard';shell();toast('已加载新演示场景，方向记录保留');break;case 'data-basis':if(['compare','trend'].includes(route))break;basis=t.value;shell();break;case 'stats-city':cityFilter=t.value;shell();break;case 'sample-mode':if(route==='compare')break;sampleMode=t.value;shell();break;case 'export-permission':S.accountExport=t.checked;log('账号导出授权', '系统管理演示账号',t.checked?'显式授予':'立即撤销');toast(t.checked?'账号导出已显式授权':'账号导出已撤销');break;case 'natureParent':$('#natureCode').innerHTML=options((nature[t.value]?.[1]||[]),'');break;case 'industryParent':$('#industryCode').innerHTML=options((industry[t.value]?.[1]||[]),'');break;case 'addressCity':$('#addressCounty').innerHTML=options([[t.value+'-K01',countyName(t.value+'-K01')]],t.value+'-K01',false);break}});
document.addEventListener('input',e=>{if(e.target.closest('#profile-form,#report-form,#period-form'))dirty=true;if(route==='report'&&['B','E'].includes(e.target.id)){const B=Number($('#B').value),E=Number($('#E').value),red=E<B;$('#change-summary').textContent=`本期岗位变化：${E-B} 人；岗位减少：${Math.max(B-E,0)} 人。`;$('#change-summary').className='callout '+(red?'warning':'');$('#reason-badge').textContent=red?'当前为减少，主要项必填':'未减少，可不填';$('#reason-badge').className='tag '+(red?'amber':'gray')}});
function updateReasonRequirements(){if(!$('#report-form'))return;const red=Number($('#E').value)<Number($('#B').value);for(const [id,needed]of [['reductionType',red],['primaryReason',red],['primaryDescription',red]]){const label=document.querySelector(`label[for="${id}"]`);let mark=label.querySelector('.required');if(needed&&!mark){mark=document.createElement('span');mark.className='required';mark.textContent=' *';label.append(mark)}if(mark)mark.hidden=!needed}}
document.addEventListener('input',e=>{if(['B','E'].includes(e.target.id))updateReasonRequirements()});
document.addEventListener('change',e=>{if(e.target.id==='primaryReason')updateReasonRequirements()});
$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))close()});
$('#dialog').addEventListener('close',()=>{if(!$('#dialog').open)$('#dialog').innerHTML=''});
seed('daily');shell();
