'use strict';
// SRS V1.1: local, deterministic interaction demonstrations. No remote requests.
const cityChoices=[['YN-C01','示例市甲'],['YN-C02','示例市乙']];
const zoneChoices=[['URBAN','城区'],['COUNTY','县域'],['RURAL','乡村']];
const baseSeed=seed,baseShell=shell,baseProfileForm=profileForm,baseFilingDecision=filingDecision;
const baseCorrectionToggle=correctionToggle,baseSaveCorrection=saveCorrection,baseExchangePage=exchangePage;
const baseReportData=reportData,baseDictPage=dictPage;
const nativeFixed=/^0\d{2,3}-?\d{7,8}$/;
const normalizePhone=s=>String(s||'').replace(/^[（(](0\d{2,3})[）)](\d{7,8})$/,'$1-$2');
const nowDate=()=>S.now.slice(0,10);
const scopeOptions=()=>Object.values(S.firms).map(f=>[f.id,f.profile.name]);
const authorId=()=>S.provinceAccount||'u4';
const actor=()=>S.users.find(u=>u.id===(S.role==='province'?authorId():S.role==='enterprise'?'u1':S.role==='city'?'u3':'u5'));
const canAccountExport=()=>S.role==='province'||S.role==='admin'&&S.accountExport;
let queryFilters={},archiveFilters={},sampleFilters={},analysisFilters={},noticeMode='read',periodEditing='2026-09';
const cleanFilters=()=>({name:'',login:'',type:'',city:'',county:'',zone:'',state:'',nature:'',industry:'',start:'',end:'',month:'',quarter:''});

seed=function(scenario='daily'){
  baseSeed(scenario);
  const c={...profile('A'),name:'示例企业丙',enterpriseCode:'C123',zoneCode:'RURAL',natureParent:'N1',natureCode:'N101',industryParent:'I4',industryCode:'I401'};
  S.firms.C={id:'C',uuid:'00000000-0000-4000-8000-000000000003',profile:c,draft:copy(c),filing:'APPROVED',profileVersion:1,change:null,baseline:20,baselineLocked:false};
  for(const f of Object.values(S.firms))f.profileHistory=f.filing==='APPROVED'?[{at:'2026-05-01 09:00',version:1,data:copy(f.profile)}]:[];
  S.users.push({id:'u6',login:'qy_c',type:'企业',firm:'C',roles:['企业'],enabled:false},{id:'u7',login:'province_b',type:'省级',roles:['省级业务'],enabled:true});
  S.users.forEach(u=>{u.createdAt='2026-09-01 09:00';u.unitName=u.firm?S.firms[u.firm].profile.name:u.type==='省级'?'省级管理单位':u.city?cityName(u.city)+'管理单位':'技术维护单位'});
  S.notices[0].authorId='u4';S.notices[0].unitName='省级管理单位';
  S.notices.push({id:'n2',title:'数据修订与历史保留说明',body:'修订另存并显式生效，历史报送快照继续保留。此通知由省级乙发布，用于验证同级可见范围。',authorId:'u7',author:'省级业务乙',unitName:'省级管理单位',createdAt:'2026-10-02 09:00',deleted:false});
  S.provinceAccount='u4';
  S.periods=[{month:'2026-09',start:S.periodStart,end:S.periodEnd}];
  S.roleTemplates=[{id:'read-province',name:'省级统计只读',identity:'省级',permissions:['stats','query']}];
  for(const r of Object.values(S.reports).filter(Boolean)){r.createdBy=r.id==='A'?'u1':'u2';r.submittedBy=r.submissionVersion?r.createdBy:null;r.snapshots.forEach(x=>x.submittedBy=r.submittedBy)}
  S.historyReports=[{...newReport('A',96,'APPROVED'),period:'2026-06',submittedAt:'2026-07-05 09:00',submittedBy:'u1',createdBy:'u1'}, {...newReport('A',90,'APPROVED'),period:'2026-08',submittedAt:'2026-09-05 09:00',submittedBy:'u1',createdBy:'u1'}];
  if(scenario==='onboarding')S.historyReports=[];
  S.historyReports.forEach(r=>{r.approvedAt=r.submittedAt;r.snapshots=[{...snapshot(r),submittedBy:'u1'}];r.events=[{action:'市、省审核通过',who:'示例审核账号',at:r.submittedAt,reason:'历史演示记录'}]});
  historyFilters={name:'',month:'',state:''};reviewFilters={name:'',month:''};sampleMode='common';
  queryFilters=cleanFilters();queryTab='accounts';archiveFilters={month:'',city:'',county:'',zone:'',name:''};sampleFilters={mode:'FILED',month:'',city:'',county:'',zone:''};
  analysisFilters={a:'2026-08',b:'2026-09',start:'2026-06',end:'2026-09',quarter:'',dimension:'city',metric:'E',city:'',nature:'',industry:''};noticeMode='read';periodEditing='2026-09';
};
meta.sample=['各市取样分析','备案企业与有效上报企业分别计数，按地区检索数量和占比。','FR-16'];
menus.province.splice(menus.province.indexOf('compare'),0,'sample');
meta.stats[2]='FR-13';meta.notices[1]='查看本人及上级通知；省级管理自己的发布记录。';
meta.archives[1]='按备案生效时间查企业档案，已备案未上报的企业也在列表中。';
reviewRules.sample=['默认备案企业：已备案未报的丙计入，甲市2家、乙市1家。','有效上报口径须选择月份；两市各1家。','市县区域筛选改变分母；饼图和表格同源。'];
reviewRules.query=['两个页签都提供13个条件，条件取交集。','账号默认含无报表、省市及停用账号。','数据状态与月份季度必须由同一报表满足；账号日期按创建日，报表按提交日。'];
reviewRules.notices=['省级甲和乙互不可浏览对方通知；企业及市级可读两者。','本人管理页包含已删除记录，普通浏览隐藏删除记录。'];
reviewRules.exchange.push('AC-10A为模拟阶段；AC-10B要求真实适配和实际国家接收凭据，原型不标记完成。');
const baseRenderPage=renderPage;
renderPage=function(){return route==='sample'?samplePage():baseRenderPage()};
shell=function(){
  baseShell();
  if(S.role==='province'){
    const el=document.createElement('div');el.className='switch-panel';
    el.innerHTML='<strong>演示账号</strong><select id="province-account" aria-label="切换省级发布账号">'+options([['u4','省级甲 · province_a'],['u7','省级乙 · province_b']],authorId(),false)+'</select><span>用于验证本人、上级与同级通知范围</span>';
    $('#main').insertBefore(el,$('#main').children[1]||null);
  }
};
profileForm=function(p,disabled){
  let html=baseProfileForm(p,disabled);
  html=html.replace(/<div class="field ?"><label for="codeDisplay">[\s\S]*?<\/div>/,field('编码类型','codeDisplay','组织机构代码 ORG9','text','系统固定类型',false,true));
  html=html.replace(/<div class="field ?"><label for="codeValue">[\s\S]*?<\/div>/,field('组织机构代码','enterpriseCode',p.enterpriseCode,'text','1至9位字母数字，企业可录入或申请变更',true,disabled));
  return html.replace('无传真填写“无”','必填带区号固话，不接受“无”').replace('1至200字</small>','1至200字，中文英文及内部空格</small>').replace('1至50字</small>','1至50字，中文英文及内部空格</small>');
};
validateProfile=function(p,submit){
  const e=[];p.codeType='ORG9';p.enterpriseCode=(p.enterpriseCode||'').toUpperCase();p.phone=normalizePhone(p.phone);p.fax=normalizePhone(p.fax);
  for(const [k,max,n]of [['name',200,'企业名称'],['business',500,'经营业务'],['contactName',50,'联系人'],['addressDetail',200,'详细地址']])if((submit||p[k])&&(!p[k]||charLen(p[k])>max))e.push(n+'必填且最多'+max+'字。');
  for(const k of ['name','contactName'])if(p[k]&&!/^[\p{Script=Han}A-Za-z ]+$/u.test(p[k]))e.push((k==='name'?'企业名称':'联系人')+'仅接受中文英文及内部空格。');
  if((submit||p.enterpriseCode)&&!/^[A-Z0-9]{1,9}$/.test(p.enterpriseCode))e.push('组织机构代码须为1至9位字母数字。');
  if(p.enterpriseCode&&Object.values(S.firms).some(f=>f.id!=='A'&&(f.profile.enterpriseCode===p.enterpriseCode||f.change?.status==='PENDING'&&f.change.data.enterpriseCode===p.enterpriseCode)))e.push('组织机构代码已被其他企业使用。');
  for(const [dict,parent,key,label]of [[nature,'natureParent','natureCode','性质'],[industry,'industryParent','industryCode','行业']])if((submit||p[key])&&!dict[p[parent]]?.[1].some(x=>x[0]===p[key]))e.push(label+'须选择合法两级分类。');
  if(S.dictDisabled.includes(p.natureCode))e.push('所选性质已停用。');
  if((submit||p.postalCode)&&!/^\d{6}$/.test(p.postalCode))e.push('邮编须为6位数字。');
  if((submit||p.phone)&&!(/^1[3-9]\d{9}$/.test(p.phone)||nativeFixed.test(p.phone)))e.push('联系电话格式不正确。');
  if((submit||p.fax)&&!nativeFixed.test(p.fax))e.push('传真必填带区号固话，不接受“无”。');
  if(p.email&&(charLen(p.email)>254||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(p.email)))e.push('邮箱格式不正确。');
  if(p.addressCounty!==p.addressCity+'-K01')e.push('地址市县不匹配。');return e;
};
validateReport=function(r,submit=true){
  const e=[];for(const k of ['B','E'])if(r[k]===''||r[k]==null){if(submit)e.push(k+'人数必填。')}else if(!Number.isInteger(Number(r[k]))||r[k]<0||r[k]>2147483647)e.push(k+'须为合法非负整数。');
  if(!submit)return e;
  if(!r.otherReason||charLen(r.otherReason)>500)e.push('其他原因须为1至500字，无情况填“无”。');
  if(r.E<r.B){if(!r.reductionType)e.push('人数减少，减少类型必填。');if(!r.primaryReason)e.push('人数减少，主要原因必填。');if(!r.primaryDescription)e.push('人数减少，主要原因说明必填。')}
  if(r.reductionType&&!rt.some(x=>x.code===r.reductionType))e.push('减少类型无效。');
  for(const k of ['primary','secondary','tertiary']){if(r[k+'Reason']&&!rc.some(x=>x.code===r[k+'Reason']))e.push('原因代码无效。');if(charLen(r[k+'Description'])>500)e.push('原因说明最多500字。')}return e;
};
reportData=function(selector,r){const data=baseReportData(selector,r);if(selector==='#report-form'){data.createdBy=r.createdBy||'u1';data.submittedBy='u1'}return data};
filingDecision=function(approve){const f=firm();baseFilingDecision(approve);if(approve&&f.filing==='APPROVED'){f.profileHistory.push({at:S.now,version:f.profileVersion,data:copy(f.profile)});shell()}};
function allReports(){return [...S.historyReports,...Object.values(S.reports).filter(Boolean)].filter(r=>!r.deleted)}
function periodRows(month){return allReports().filter(r=>r.period===month&&r.status==='APPROVED')}
function reportUser(r){return S.users.find(u=>u.id===(r.submittedBy||r.createdBy||(r.id==='A'?'u1':'u2')))}
function regionFields(prefix,v){return selectField('所属地市',prefix+'city',cityChoices,v.city)+selectField('所属市县',prefix+'county',cityChoices.filter(c=>!v.city||c[0]===v.city).map(c=>[c[0]+'-K01',countyName(c[0]+'-K01')]),v.county)+selectField('所处区域',prefix+'zone',zoneChoices,v.zone)}
function regionMatch(p,f){return(!f.city||p.cityCode===f.city)&&(!f.county||p.countyCode===f.county)&&(!f.zone||p.zoneCode===f.zone)}
function filedAt(f,month){const cutoff=month?Math.min(new Date(month+'-01T00:00:00+08:00').getTime()+32*864e5,new Date(S.now.replace(' ','T')+'+08:00').getTime()):Infinity;return [...f.profileHistory].reverse().find(v=>!month||v.at.slice(0,7)<=month&&new Date(v.at.replace(' ','T')+'+08:00').getTime()<=cutoff)}
function archiveRows(){return Object.values(S.firms).map(f=>({f,v:filedAt(f,archiveFilters.month)})).filter(x=>x.v&&regionMatch(x.v.data,archiveFilters)&&x.v.data.name.includes(archiveFilters.name||''))}
archivesPage=function(){const rows=archiveRows();return header('archives',btn('导出全部命中 · 预览','export-preview'))+`<section class="card"><div class="form-grid">${field('调查月份','ar-month',archiveFilters.month,'month','留空取当前备案，选择月份取月末已生效档案')}${field('企业名称','ar-name',archiveFilters.name)}${regionFields('ar-',archiveFilters)}</div><div class="form-actions">${btn('查询','archive-search','primary')}${btn('清除','archive-clear')}</div><div id="form-errors" class="errors"></div></section><section class="card"><h2>已备案企业 · ${rows.length} 家</h2>${rows.length?table(['企业','代码','地区','备案生效 / 版本','当期报送','操作'],rows.map(({f,v})=>tr([esc(v.data.name),esc(v.data.enterpriseCode),cityName(v.data.cityCode)+' / '+countyName(v.data.countyCode),v.at+' / v'+v.version,archiveFilters.month?(allReports().some(r=>r.id===f.id&&r.period===archiveFilters.month&&r.submissionVersion)?'已提交':'未提交'):'未限定月份',btn('只读详情','archive-detail','small',false,f.id)]))):empty('暂无匹配备案企业','可以清除地区或月份条件。')}<p class="muted">包含已备案但未建报、草稿和待审企业；列表详情与导出采用同一筛选。</p></section>`};
function quarterMatch(month,q){return !q||q===month.slice(0,4)+'-Q'+Math.ceil(Number(month.slice(5))/3)}
function queryRows(){
  const f=queryFilters;let rows;
  if(queryTab==='accounts')rows=S.users.filter(u=>!u.deleted).filter(u=>{const p=S.firms[u.firm]?.profile||{name:u.unitName,cityCode:u.city};const related=allReports().filter(r=>r.id===u.firm);return matchCommon(p,u,f)&&dateMatch(u.createdAt,f)&&(!(f.state||f.month||f.quarter)||related.some(r=>matchReport(r,f)))});
  else rows=allReports().filter(r=>matchCommon(r.profile,reportUser(r)||{},f)&&matchReport(r,f)&&dateMatch(r.submittedAt,f));
  return rows.sort((a,b)=>String(queryTab==='accounts'?b.createdAt:b.submittedAt||'').localeCompare(String(queryTab==='accounts'?a.createdAt:a.submittedAt||''))||String(b.id).localeCompare(String(a.id)));
}
function matchCommon(p,u,f){return (p.name||'').includes(f.name)&&String(u.login||'').toLowerCase().includes(f.login.toLowerCase())&&(!f.type||u.type===f.type)&&regionMatch(p,f)&&(!f.nature||p.natureCode===f.nature)&&(!f.industry||p.industryCode===f.industry)}
function matchReport(r,f){return(!f.state||r.status===f.state)&&(!f.month||r.period===f.month)&&quarterMatch(r.period,f.quarter)}
function dateMatch(date,f){return(!f.start||date&&date.slice(0,10)>=f.start)&&(!f.end||date&&date.slice(0,10)<=f.end)}
function accountRows(rows){return rows.map(u=>tr([esc(u.login),esc(u.type),esc(S.firms[u.firm]?.profile.name||u.unitName),u.enabled?'启用':'停用',esc(u.createdAt),esc(u.roles.join('、')||'无角色')]))}
queryPage=function(){const f=queryFilters,rows=queryRows();return header('query',btn('导出全部命中 · 预览','export-preview'))+`<div class="tabs">${btn('账号查询','query-accounts',queryTab==='accounts'?'selected':'')}${btn('企业报表','query-reports',queryTab==='reports'?'selected':'')}</div><section class="card"><div class="form-grid query-grid">${field('单位名称','q-name',f.name)}${field('登录账号','q-login',f.login)}${selectField('用户类型','q-type',['企业','市级','省级','系统管理'].map(x=>[x,x]),f.type)}${regionFields('q-',f)}${selectField('数据状态','q-state',['DRAFT','CITY_PENDING','CITY_RETURNED','PROVINCE_PENDING','PROVINCE_RETURNED','APPROVED'].map(s=>[s,statuses[s][0]]),f.state)}${selectField('单位性质','q-nature',Object.values(nature).flatMap(v=>v[1]),f.nature)}${selectField('所属行业','q-industry',Object.values(industry).flatMap(v=>v[1]),f.industry)}${field('起始日期','q-start',f.start,'date',queryTab==='accounts'?'按账号创建日':'按最近正式提交日')}${field('结束日期','q-end',f.end,'date','包含结束日全天')}${field('统计月份','q-month',f.month,'month')}${selectField('统计季度','q-quarter',['Q1','Q2','Q3','Q4'].map(q=>['2026-'+q,'2026年 '+q]),f.quarter)}</div><div class="form-actions">${btn('查询','query-search','primary')}${btn('清除全部条件','query-clear')}</div><div id="form-errors" class="errors" role="alert"></div></section><section class="card"><h2>查询结果 · <span id="query-count">${rows.length}</span> 条</h2>${rows.length?(queryTab==='accounts'?table(['账号','用户类型','单位名称','账号启停','创建时间','角色'],accountRows(rows)):table(['企业','所属市','月份','B / E','数据状态','提交版本','操作'],rows.map(r=>tr([esc(r.profile.name),cityName(r.profile.cityCode),r.period,r.B+' / '+r.E,badge(r.status),'v'+r.submissionVersion,btn('查看详情','query-detail','small',false,r.id+'|'+r.period)])))):empty('没有匹配结果','清除或调整筛选条件。')}<p class="muted">${queryTab==='accounts'?'未使用报表条件时，无报表、省市、停用账号均保留；同一账号只出现一次。':'按每企业每调查期显示当前状态。'} · 示例记录不足20条，当前为第1页。</p></section>`};
function readFilter(prefix,keys){return Object.fromEntries(keys.map(k=>[k,$('#'+prefix+k)?.value.trim()||'']))}
function filterErrors(f){return[f.start&&f.end&&f.start>f.end?'开始日期不能晚于结束日期。':'',f.month&&f.quarter&&!quarterMatch(f.month,f.quarter)?'月份不属于所选季度。':'',f.county&&f.city&&!f.county.startsWith(f.city+'-')?'所选市县不匹配。':''].filter(Boolean)}
function sampleRows(){const f=sampleFilters;return f.mode==='FILED'?Object.values(S.firms).map(x=>filedAt(x,f.month)).filter(Boolean).map(v=>v.data).filter(p=>regionMatch(p,f)):periodRows(f.month).map(r=>r.profile).filter(p=>regionMatch(p,f))}
function pieChart(groups){const total=groups.reduce((n,g)=>n+g.value,0);if(!total)return empty('暂无样本','没有匹配企业，比例不可计算。');let angle=0;const stops=groups.map((g,i)=>{const start=angle;angle+=g.value/total*100;return `${['#245bce','#12a18a','#e9a13b'][i%3]} ${start}% ${angle}%`});return `<div class="pie-wrap"><div class="pie" role="img" aria-label="各市企业数量占比饼图" style="background:conic-gradient(${stops.join(',')})"><span>${total}<small>样本企业</small></span></div><div>${groups.map((g,i)=>`<p><i class="legend-dot" style="background:${['#245bce','#12a18a','#e9a13b'][i%3]}"></i>${esc(g.name)} · ${g.value}家 · ${pct(g.value/total*100)}</p>`).join('')}</div></div>`}
function samplePage(){const f=sampleFilters,rows=sampleRows(),groups=cityChoices.map(([c,n])=>({name:n,value:rows.filter(p=>p.cityCode===c).length}));return header('sample')+`<section class="card"><div class="form-grid">${selectField('取样口径','s-mode',[['FILED','备案企业（默认）'],['REPORTED','有效上报企业']],f.mode)}${field('调查月份','s-month',f.month,'month',f.mode==='FILED'?'留空查看当前备案企业':'有效上报必须选择月份')}${regionFields('s-',f)}</div><div class="form-actions">${btn('查询分析','sample-search','primary')}${btn('清除','sample-clear')}</div><div id="form-errors" class="errors"></div></section><div class="grid two"><section class="card"><h2>各市分布 · ${f.mode==='FILED'?'备案企业':'有效上报企业'}</h2>${pieChart(groups)}<p class="muted">分母为当前地区筛选后的 ${rows.length} 家企业，舍入后占比之和可能有尾差。</p></section><section class="card"><h2>数量与占比</h2>${table(['地区','企业数','占比'],groups.map(g=>tr([g.name,g.value,pct(rows.length?g.value/rows.length*100:null)])))}<h3 class="section-gap">命中企业</h3>${rows.map(p=>`<span class="tag gray">${esc(p.name)}</span>`).join(' ')||'无'}<p class="muted section-gap">备案口径包含已备案未报的丙；有效上报口径只计省审通过且未删除的月报。</p></section></div>`}
const baseStatsPage=statsPage;
statsPage=function(){return baseStatsPage().replace('<h2>各市取样企业占比</h2>','<h2>有效上报企业分布</h2><p>备案企业取样请进入独立的“各市取样分析”。</p>'+btn('查看备案取样饼图','go-sample','small'))};
function analysisRows(month){return periodRows(month).filter(r=>(!analysisFilters.city||r.profile.cityCode===analysisFilters.city)&&(!analysisFilters.nature||r.profile.natureCode===analysisFilters.nature)&&(!analysisFilters.industry||r.profile.industryCode===analysisFilters.industry))}
function lineChart(labels,values,title){const valid=values.filter(v=>v!==null),min=Math.min(0,...valid),max=Math.max(1,...valid),Y=v=>160-(v-min)/(max-min)*130,X=i=>50+i*650/Math.max(1,labels.length-1);let segments=[],part=[];values.forEach((v,i)=>{if(v===null){if(part.length)segments.push(part);part=[]}else part.push([X(i),Y(v),i,v])});if(part.length)segments.push(part);return `<svg class="chart" viewBox="0 0 760 225" role="img" aria-label="${esc(title)}"><title>${esc(title)}</title><line x1="35" y1="170" x2="725" y2="170"/>${segments.map(a=>`<polyline points="${a.map(p=>p[0]+','+p[1]).join(' ')}"/>`+a.map(([x,y,i,v])=>`<circle cx="${x}" cy="${y}" r="5"/><text x="${x}" y="${y-12}" text-anchor="middle">${Math.round(v*100)/100}</text>`).join('')).join('')}${labels.map((l,i)=>`<text x="${X(i)}" y="200" text-anchor="middle">${esc(l)}</text>${values[i]===null?`<text x="${X(i)}" y="100" text-anchor="middle">缺失</text>`:''}`).join('')}</svg>`}
function analysisControls(trend=false){const f=analysisFilters;return `<div class="form-grid">${trend?field('开始月份','a-start',f.start,'month')+field('结束月份','a-end',f.end,'month')+selectField('季度快捷筛选','a-quarter',[['2026-Q2','2026年第二季度'],['2026-Q3','2026年第三季度']],f.quarter):field('第一调查期','a-a',f.a,'month')+field('第二调查期','a-b',f.b,'month')+selectField('分组维度','a-dimension',[['city','地区'],['nature','企业性质'],['industry','行业']],f.dimension)}${selectField('所属市','a-city',cityChoices,f.city)}${selectField('企业性质','a-nature',Object.values(nature).flatMap(v=>v[1]),f.nature)}${selectField('所属行业','a-industry',Object.values(industry).flatMap(v=>v[1]),f.industry)}${!trend?selectField('图表指标','a-metric',[['N','企业数'],['B','建档总岗位'],['E','调查总岗位'],['D','岗位变化'],['L','岗位减少'],['R','变化比例']],f.metric)+selectField('样本方式','sample-mode',[['common','共同企业'],['independent','各期独立']],sampleMode):''}${selectField('人数口径','data-basis',[['ORIGINAL','原始有效口径'],['CORRECTED','修订有效口径']],basis)}</div><div class="form-actions">${btn('应用分析条件',trend?'trend-apply':'compare-apply','primary')}</div><div id="form-errors" class="errors"></div>`}
function comparisonData(){const a=periodRows(analysisFilters.a),b=periodRows(analysisFilters.b),ids=new Set(a.filter(r=>b.some(v=>v.id===r.id)).map(r=>r.id));const common=sampleMode==='common';const get=(rows)=>rows.filter(r=>!common||ids.has(r.id)).map(r=>{const later=analysisFilters.a>analysisFilters.b?a:b;return common?{...r,profile:later.find(v=>v.id===r.id).profile}:r}).filter(r=>regionMatch(r.profile,{city:analysisFilters.city})&&(!analysisFilters.nature||r.profile.natureCode===analysisFilters.nature)&&(!analysisFilters.industry||r.profile.industryCode===analysisFilters.industry));return{a:get(a),b:get(b),added:b.filter(r=>!a.some(v=>v.id===r.id)).length,missing:a.filter(r=>!b.some(v=>v.id===r.id)).length}}
comparePage=function(){const d=comparisonData(),a=totals(d.a),b=totals(d.b),dim=analysisFilters.dimension,key={city:'cityCode',nature:'natureCode',industry:'industryCode'}[dim],groupName=c=>dim==='city'?cityName(c):nameOf(dim==='nature'?nature:industry,c),groups=[...new Set([...d.a,...d.b].map(r=>r.profile[key]))];return header('compare')+`<section class="card">${analysisControls()}</section><section class="card"><h2>两期六指标 · ${sampleMode==='common'?'共同样本':'独立样本'}</h2><p>第一期新增到第二期 ${d.added} 家，第二期缺失 ${d.missing} 家。共同样本使用较晚期资料分组。</p>${table(['指标',analysisFilters.a,analysisFilters.b],[['企业数','N'],['建档总岗位','B'],['调查总岗位','E'],['岗位变化','D'],['岗位减少','L'],['变化比例','R']].map(([n,k])=>tr([n,k==='R'?pct(a[k]):a[k],k==='R'?pct(b[k]):b[k]])))}${lineChart([analysisFilters.a,analysisFilters.b],[a[analysisFilters.metric],b[analysisFilters.metric]],'两期指标对比折线图')}<h3>按${{city:'地区',nature:'企业性质',industry:'行业'}[dim]}分组</h3>${groups.length?table(['分组（第一期 → 第二期）','企业数 N','建档岗位 B','调查岗位 E','岗位变化 D','岗位减少 L','比例 R'],groups.map(g=>{const x=totals(d.a.filter(r=>r.profile[key]===g)),y=totals(d.b.filter(r=>r.profile[key]===g));return tr([esc(groupName(g)),...['N','B','E','D','L','R'].map(k=>(k==='R'?pct(x[k]):x[k])+' → '+(k==='R'?pct(y[k]):y[k]))])})):empty('无共同或有效样本','尝试独立样本或其他月份。')}<h3 class="section-gap">岗位变化柱状图</h3><div class="change-bars">${[a,b].map((v,i)=>`<div><strong>${[analysisFilters.a,analysisFilters.b][i]}</strong><div class="signed-bar ${v.D<0?'negative':''}" style="width:${Math.max(2,Math.abs(v.D)/Math.max(1,Math.abs(a.D),Math.abs(b.D))*90)}%"></div><span>${v.D>0?'+':''}${v.D} 人</span></div>`).join('')}</div></section>`};
trendPage=function(){const f=analysisFilters,months=[];let d=new Date(f.start+'-01T00:00:00Z');for(let i=0;i<24&&d.toISOString().slice(0,7)<=f.end;i++,d.setUTCMonth(d.getUTCMonth()+1))months.push(d.toISOString().slice(0,7));const data=months.map(m=>{const rows=analysisRows(m),t=totals(rows);return{month:m,n:rows.length,value:rows.length?t.R:null}});return header('trend')+`<section class="card">${analysisControls(true)}</section><section class="card"><h2>连续月份岗位变化比例</h2>${lineChart(data.map(x=>x.month),data.map(x=>x.value),'连续月岗位变化比例，缺月断线')}${table(['月份','企业数','变化比例','说明'],data.map(x=>tr([x.month,x.n,pct(x.value),x.n?(x.value===null?'建档总数为0':'当期独立有效样本'):'缺失，不补0'])))}<p class="muted">6月甲100/96为−4%；8月甲100/90为−10%；9月来自本轮审核结果。所有比例均由表中样本计算。季度只筛月份。</p></section>`};
correctionPage=function(){const rows=Object.values(S.reports).filter(r=>r&&!r.deleted&&['PROVINCE_PENDING','APPROVED'].includes(r.status));return header('correction',btn('未来基准规划','baseline-new'))+`<div class="callout">待省审可另存，省审通过后才可生效；修订绑定提交版本，退回重提后不得套用旧修订。</div><section class="card">${rows.length?table(['企业','原始 B / E','修订 B / E','审核状态','修订状态','操作'],rows.map(r=>tr([esc(r.profile.name),r.B+' / '+r.E,r.revisionDraft?r.revisionDraft.data.B+' / '+r.revisionDraft.data.E:r.revision?.active?r.revision.data.B+' / '+r.revision.data.E:'—',badge(r.status),r.revisionDraft?'已保存未生效':r.revision?.active?'已生效':'无',btn('另存修订','correction-edit','small',false,r.id)+(r.revisionDraft?btn('生效','correction-activate','primary small',r.status!=='APPROVED',r.id):r.revision?.active?btn('撤销生效','correction-revoke','small',false,r.id):'')]))):empty('暂无可修订报表','等待企业提交并通过市审。')}</section>`};
saveCorrection=function(){baseSaveCorrection();const r=rep();if(r?.revisionDraft)r.revisionDraft.submissionVersion=r.submissionVersion};
correctionToggle=function(id,active){const r=S.reports[id];if(active&&(r.status!=='APPROVED'||r.revisionDraft?.submissionVersion!==r.submissionVersion))return toast('当前提交版本尚未通过省审或修订已过期');baseCorrectionToggle(id,active)};
const baseSaveReport=saveReport;
saveReport=function(submit){const version=S.reports.A?.submissionVersion||0;baseSaveReport(submit);const r=S.reports.A;if(submit&&r?.submissionVersion>version&&r.revisionDraft){r.expiredRevisions||=[];r.expiredRevisions.push(r.revisionDraft);r.revisionDraft=null}};
exchangePage=function(){return baseExchangePage()+`<section class="card"><h2>国家交换验收方向</h2><div class="grid two"><div class="acceptance-card"><span class="tag">AC-10A · 本地阶段</span><p>演示模拟成功、部分拒绝、认证失败、未知结果及补发。当前批次结果仅属于原型。</p></div><div class="acceptance-card"><span class="tag amber">AC-10B · 实际接入未执行</span><p>正式交付须有真实适配代码、协议与编码映射、认证、实际发送和可核验接收凭据。此原型没有真实发送功能。</p></div></div></section>`};
function visibleNotices(){return S.notices.filter(n=>S.role==='province'?n.authorId===authorId()&&(noticeMode==='manage'||!n.deleted):!n.deleted)}
noticesPage=function(){const rows=visibleNotices();return header('notices',S.role==='province'?btn('发布通知','notice-new','primary'):'')+(S.role==='province'?`<div class="tabs">${btn('本人及上级通知','notice-read',noticeMode==='read'?'selected':'')}${btn('本人发布管理（含删除）','notice-manage',noticeMode==='manage'?'selected':'')}</div>`:'')+`<section class="card">${rows.length?rows.map(n=>`<article class="notice"><div class="split-summary"><h3>${esc(n.title)} ${n.deleted?'<span class="tag gray">已删除</span>':''}</h3>${S.role==='province'&&noticeMode==='manage'&&!n.deleted?btn('修改','notice-edit','small',false,n.id)+btn('删除','notice-delete','danger small',false,n.id):''}</div><p class="meta">${esc(n.unitName)} · ${esc(n.createdAt)} · ${esc(n.author)}</p><p>${esc(n.body)}</p></article>`).join(''):empty('暂无可见通知','当前只显示本人及上级发布的有效通知。')}<p class="muted section-gap">${S.role==='province'?'省级在系统内无更高层级，同级另一省级账号的通知不可见。':'省级为当前账号的上级，停用发布账号不会撤销其已发布通知。'}</p></section>`};
openNotice=function(id){const n=S.notices.find(v=>v.id===id);if(id&&(!n||n.deleted||n.authorId!==authorId()))return toast('无权修改此通知');activeId=id||'';modal(id?'修改本人通知':'发布省级通知',`<div id="modal-errors" class="errors"></div><div class="form-grid">${field('标题','notice-title',n?.title||'','text','1至50字',true,false,true)}${area('内容','notice-body',n?.body||'','1至2000字，纯文本',true)}</div><p>单位自动取发布账号：${esc(actor().unitName)}；首次发布时间保留。</p>`,btn('保存通知','notice-save','primary'))};
saveNotice=function(){if(!requireRole('province'))return;const title=$('#notice-title').value.trim(),body=$('#notice-body').value.trim();if(!title||charLen(title)>50||!body||charLen(body)>2000)return errorMessages(['标题1至50字，内容1至2000字。']);const n=S.notices.find(v=>v.id===activeId);if(n&&(n.authorId!==authorId()||n.deleted))return toast('仅可修改本人有效通知');if(n)Object.assign(n,{title,body,updatedAt:S.now});else S.notices.unshift({id:uid(),title,body,authorId:authorId(),author:authorId()==='u4'?'省级业务甲':'省级业务乙',unitName:actor().unitName,createdAt:S.now,deleted:false});log('保存通知',title);close();shell();toast('已保存；本人及下级可以阅读')};
usersPage=function(){return header('users',btn('新增账号','user-new','primary')+btn('账号导出预览','export-preview','',!canAccountExport()))+`<div class="callout">${S.role==='province'?'默认省级可管理全省账号、角色并直接导出。':'技术管理维护账号，账号导出需显式授权。'}有本人正式提交数据的账号不能删除。</div><section class="card">${table(['账号','身份 / 单位','角色','状态','操作'],S.users.filter(u=>!u.deleted).map(u=>tr([esc(u.login),esc(u.type+' / '+(S.firms[u.firm]?.profile.name||u.unitName)),esc(u.roles.join('、')||'无角色'),u.enabled?'启用':'停用',btn('修改','user-edit','small',false,u.id)+btn('角色','user-role','small',false,u.id)+btn(u.enabled?'停用':'启用','user-toggle','small',false,u.id)+btn('删除','user-delete','danger small',false,u.id)])))}</section>`};
function editUser(id){activeId=id;const u=S.users.find(x=>x.id===id);modal('修改账号资料',`<div id="modal-errors" class="errors"></div><div class="form-grid">${field('登录账号','edit-login',u.login,'text','3至64位，大小写唯一',true)}${field('单位名称','edit-unit',u.unitName,'text','通知发布时冻结该名称',true)}${u.type==='市级'?selectField('所属市','edit-city',cityChoices,u.city):''}</div><p>业务身份及已绑定企业保持不变；角色在独立入口管理。</p>`,btn('保存修改','user-edit-save','primary'))}
function saveUserEdit(){const u=S.users.find(x=>x.id===activeId),login=$('#edit-login').value.trim(),unit=$('#edit-unit').value.trim();if(!/^[A-Za-z0-9_-]{3,64}$/.test(login)||!unit||charLen(unit)>200||S.users.some(x=>x.id!==u.id&&x.login.toLowerCase()===login.toLowerCase()))return errorMessages(['账号格式或唯一性不合法，单位名称须为1至200字。']);Object.assign(u,{login,unitName:unit});if($('#edit-city'))u.city=$('#edit-city').value;log('修改账号',login);close();shell()}
function lastManager(u){return u.enabled&&!u.deleted&&u.roles.some(r=>['省级业务','系统管理'].includes(r))&&!S.users.some(x=>x.id!==u.id&&!x.deleted&&x.enabled&&x.roles.some(r=>['省级业务','系统管理'].includes(r)))}
const baseUserSave=userSave;
userSave=function(){
 if(!requireRole('admin'))return;const login=$('#user-login').value.trim(),type=$('#user-type').value,firmId=$('#user-firm').value,city=$('#user-city').value;
 if(!['企业','市级','省级'].includes(type)||type==='企业'&&!S.firms[firmId]||type==='市级'&&!cityChoices.some(c=>c[0]===city)||!/^[A-Za-z0-9_-]{3,64}$/.test(login)||S.users.some(u=>u.login.toLowerCase()===login.toLowerCase()))return errorMessages(['账号格式、归属或唯一性不合法。']);
 if(S.role==='admin'&&type==='省级')return errorMessages(['省级业务账号须由省级身份创建授权。']);
 S.users.push({id:uid(),login,type,firm:type==='企业'?firmId:null,city:type==='市级'?city:null,roles:[{企业:'企业',市级:'市级审核',省级:'省级业务'}[type]],enabled:true,createdAt:S.now,unitName:type==='企业'?S.firms[firmId].profile.name:type==='省级'?'省级管理单位':cityName(city)+'管理单位'});log('创建账号',login);close();shell();toast('示例账号已创建；未产生真实凭据');
};
rolesPage=function(){return header('roles',btn('新增自定义角色','role-new','primary'))+`<section class="card">${table(['预置角色','范围','能力'],[['企业','自身企业','资料、月报、历史、通知，无导出'],['市级审核','所属市','审核、历史、通知，无导出'],['省级业务','全省','全部省级业务及用户、角色、调查期、字典、监控和三类导出'],['系统管理','配置及运行','用户角色配置、调查期、字典、监控；无隐式省级业务权限']].map(tr))}<div class="checks section-gap"><label><input id="export-permission" type="checkbox" ${S.accountExport?'checked':''}>显式授予技术管理账号导出权限（省级默认已具备）</label></div></section><section class="card"><h2>自定义角色</h2>${S.roleTemplates.length?table(['名称','业务身份','功能','关联用户','操作'],S.roleTemplates.map(r=>tr([esc(r.name),r.identity,r.permissions.map(k=>esc(meta[k][0])).join('、'),S.users.filter(u=>!u.deleted&&u.roles.includes(r.name)).length,btn('修改','role-edit','small',false,r.id)+btn('删除','role-delete','danger small',false,r.id)]))):empty('暂无自定义角色','可新增角色，之后在用户管理中分配。')}</section>`};
function editRole(id){activeId=id||'';const r=S.roleTemplates.find(x=>x.id===id);modal(id?'修改自定义角色':'新增自定义角色',`<div id="modal-errors" class="errors"></div>${field('角色名称','custom-role-name',r?.name||'','text','1至50字，不能与预置或现有角色重复',true)}${selectField('业务身份','custom-role-identity',['企业','市级','省级'].map(x=>[x,x]),r?.identity||'省级')}<h3 class="section-gap">选择功能</h3><div class="checks">${['profile','report','history','review','stats','query','notices'].map(k=>`<label><input type="checkbox" name="custom-permission" value="${k}" ${r?.permissions.includes(k)?'checked':''}>${meta[k][0]}</label>`).join('')}</div><p>按身份限制功能：企业不能获得全省查询，市级不能获得省级统计与导出。</p>`,btn('保存角色','role-save','primary'))}
function saveRole(){const name=$('#custom-role-name').value.trim(),identity=$('#custom-role-identity').value,permissions=[...document.querySelectorAll('[name="custom-permission"]:checked')].map(x=>x.value),allowed={企业:['profile','report','history','notices'],市级:['review','history','notices'],省级:['review','stats','query','notices']};if(!name||charLen(name)>50||['企业','市级审核','省级业务','系统管理'].includes(name)||S.roleTemplates.some(r=>r.id!==activeId&&r.name===name)||!permissions.length||permissions.some(k=>!allowed[identity].includes(k)))return errorMessages(['名称须唯一且1至50字，至少选择一个符合业务身份的功能。']);if(S.role==='admin'&&identity==='省级')return errorMessages(['技术管理不能授予省级业务角色，请由省级操作。']);const r=S.roleTemplates.find(x=>x.id===activeId);if(r){const linked=S.users.filter(u=>u.roles.includes(r.name));if(linked.some(u=>u.type!==identity))return errorMessages(['角色已分配，不能更改为不匹配的身份。']);linked.forEach(u=>u.roles=u.roles.map(v=>v===r.name?name:v));Object.assign(r,{name,identity,permissions})}else S.roleTemplates.push({id:uid(),name,identity,permissions});log('保存角色',name);close();shell()}
openUserRoles=function(id){activeId=id;const u=S.users.find(x=>x.id===id),own={'企业':'企业','市级':'市级审核','省级':'省级业务','系统管理':'系统管理'}[u.type],choices=[own,...(u.type==='省级'?['系统管理']:[]),...S.roleTemplates.filter(r=>r.identity===u.type).map(r=>r.name)];modal('分配账号角色',`<div id="modal-errors" class="errors"></div><p>${esc(u.login)} · ${u.type}</p><div class="checks">${choices.map(r=>`<label><input name="user-role-check" type="checkbox" value="${esc(r)}" ${u.roles.includes(r)?'checked':''}>${esc(r)}</label>`).join('')}</div><p>无角色账号保留记录并停止业务；重新分配后可恢复。</p>`,btn('保存角色','user-role-save','primary'))};
userRolesSave=function(){const u=S.users.find(x=>x.id===activeId),chosen=[...document.querySelectorAll('[name="user-role-check"]:checked')].map(x=>x.value);if(S.role==='admin'&&u.type==='省级'&&chosen.some(r=>r!=='系统管理'))return errorMessages(['省级业务角色由省级账号授权。']);if(lastManager(u)&&!chosen.some(r=>['省级业务','系统管理'].includes(r)))return errorMessages(['不能撤去最后一个有效管理账号的管理权限。']);u.roles=chosen;log('分配角色',u.login,chosen.join('、')||'无角色');close();shell()};
periodsPage=function(){return header('periods',btn('新增调查期','period-new','primary'))+`<section class="card">${table(['调查月份','开始时间','截止时间（不含）','操作'],S.periods.map(p=>tr([p.month,p.start.replace('T',' '),p.end.replace('T',' '),btn('修改窗口','period-edit','small',false,p.month)])))}</section><section class="card"><h2>修改 ${periodEditing} 调查期</h2><form id="period-form"><div id="form-errors" class="errors"></div><div class="form-grid">${field('调查月份','period',periodEditing,'month','已有记录的年月锁定',true,true)}${field('开始时间','periodStart',S.periods.find(p=>p.month===periodEditing).start,'datetime-local','包含开始',true)}${field('截止时间','periodEnd',S.periods.find(p=>p.month===periodEditing).end,'datetime-local','不含截止',true)}</div><div class="form-actions">${btn('保存调查期配置','period-save','primary')}</div></form></section>`};
function periodNew(){modal('新增调查期',`<div id="modal-errors" class="errors"></div><div class="form-grid">${field('调查月份','new-period','2026-10','month','模板加月份唯一',true)}${field('开始时间','new-start','2026-11-01T00:00','datetime-local','上海时区',true)}${field('截止时间','new-end','2026-11-11T00:00','datetime-local','不含截止',true)}</div>`,btn('创建调查期','period-create','primary'))}
codeCorrect=function(id){activeId=id;const f=firm();modal('所属地区纠错',`<div id="modal-errors" class="errors"></div><p>${esc(f.profile.name)} · 编码 ${esc(f.profile.enterpriseCode)}。编码由企业资料变更入口申请修改。</p><div class="form-grid">${selectField('所属市','codeCity',cityChoices,f.profile.cityCode,'县跟随示例市',true)}${selectField('区域','codeZone',zoneChoices,f.profile.zoneCode,'',true)}${area('纠错理由','code-reason','','必填，保留历史快照',true)}</div>`,btn('保存地区版本','code-save','primary'))};
codeSave=function(){if(!requireRole('admin'))return;const reason=$('#code-reason').value.trim(),city=$('#codeCity').value,zone=$('#codeZone').value;if(!reason||charLen(reason)>500||!cityChoices.some(x=>x[0]===city)||!zoneChoices.some(x=>x[0]===zone))return errorMessages(['选择合法地区，理由1至500字。']);const f=firm();Object.assign(f.profile,{cityCode:city,countyCode:city+'-K01',zoneCode:zone});f.profileVersion++;f.profileHistory.push({at:S.now,version:f.profileVersion,data:copy(f.profile)});f.draft=copy(f.profile);log('地区纠错',f.profile.name,reason);close();shell()};
exportPreview=function(){if(!['province','admin'].includes(S.role)||S.role==='admin'&&!S.accountExport)return toast('当前账号没有导出权限');const kind=route==='users'||route==='query'&&queryTab==='accounts'?'accounts':route==='archives'?'firms':'reports',rows=route==='query'?queryRows():route==='archives'?archiveRows():route==='users'?S.users.filter(u=>!u.deleted):validReports();log('导出预览',meta[route][0],rows.length+'条');modal('XLSX导出预览',`<div class="callout">需求原型仅预览导出结构；正式文件生成由业务实现完成。</div>${pair('命中记录数',`<span id="export-count">${rows.length}</span> 条（全部命中）`)}${pair('数据集',{accounts:'账号列表',firms:'企业信息',reports:'企业报表'}[kind])}${pair('工作表','数据 + 查询说明')}${pair('生成行为','超过10,000行异步；下载24小时有效，再次鉴权')}<h3 class="section-gap">列顺序</h3><p>${exportColumns[kind].map(x=>`<span class="tag gray">${esc(x)}</span>`).join(' ')}</p><h3>查询说明</h3><pre class="pre">${esc(JSON.stringify({筛选:route==='query'?queryFilters:route==='archives'?archiveFilters:{city:cityFilter},口径:basis,记录数:rows.length},null,2))}</pre>`)};
exportColumns.firms.push('备案生效时间','当期是否上报');
const originalActions={...actionHandlers};
Object.assign(actionHandlers,{
 'go-sample':()=>go('sample'),
 'archive-search':()=>{archiveFilters=readFilter('ar-',['month','city','county','zone','name']);if(filterErrors(archiveFilters).length)return errorMessages(filterErrors(archiveFilters));shell()},
 'archive-clear':()=>{archiveFilters={month:'',city:'',county:'',zone:'',name:''};shell()},
 'archive-detail':id=>{const v=filedAt(S.firms[id],archiveFilters.month);if(v)modal('备案档案 · 只读',profileForm(v.data,true))},
 'query-search':()=>{const f=readFilter('q-',Object.keys(cleanFilters())),e=filterErrors(f);if(e.length)return errorMessages(e);queryFilters=f;shell()},
 'query-clear':()=>{queryFilters=cleanFilters();shell()},
 'query-accounts':()=>{if(route==='query')queryFilters=readFilter('q-',Object.keys(cleanFilters()));queryTab='accounts';shell()},
 'query-reports':()=>{if(route==='query')queryFilters=readFilter('q-',Object.keys(cleanFilters()));queryTab='reports';shell()},
 'query-detail':key=>{const [id,month]=key.split('|'),r=allReports().find(r=>r.id===id&&r.period===month);if(r)modal('报表详情 · 只读',reportDetail(r))},
 'sample-search':()=>{const f=readFilter('s-',['mode','month','city','county','zone']);if(f.mode==='REPORTED'&&!f.month)return errorMessages(['有效上报口径必须选择调查月份。']);if(filterErrors(f).length)return errorMessages(filterErrors(f));sampleFilters=f;shell()},
 'sample-clear':()=>{sampleFilters={mode:'FILED',month:'',city:'',county:'',zone:''};shell()},
 'compare-apply':()=>{const f={...analysisFilters,...readFilter('a-',['a','b','dimension','metric','city','nature','industry'])};if(!f.a||!f.b||f.a===f.b)return errorMessages(['请选择两个不同调查期。']);analysisFilters=f;shell()},
 'trend-apply':()=>{const f={...analysisFilters,...readFilter('a-',['start','end','quarter','city','nature','industry'])};if(f.quarter){const q=Number(f.quarter.at(-1));f.start='2026-'+String(q*3-2).padStart(2,'0');f.end='2026-'+String(q*3).padStart(2,'0')}if(!f.start||!f.end||f.start>f.end||(Number(f.end.slice(0,4))*12+Number(f.end.slice(5)))-(Number(f.start.slice(0,4))*12+Number(f.start.slice(5)))>=24)return errorMessages(['连续区间须为1至24个月，开始不得晚于结束。']);analysisFilters=f;shell()},
 'export-preview':exportPreview,'filing-approve':()=>filingDecision(true),'filing-return':()=>filingDecision(false),
 'correction-save':saveCorrection,'correction-activate':id=>{if(S.reports[id].status!=='APPROVED')return toast('需省审通过后生效');originalActions['correction-activate'](id)},
 'notice-new':()=>openNotice(''),'notice-edit':openNotice,'notice-save':saveNotice,'notice-read':()=>{noticeMode='read';shell()},'notice-manage':()=>{noticeMode='manage';shell()},
 'notice-delete':id=>{const n=S.notices.find(n=>n.id===id);if(!n||n.authorId!==authorId()||n.deleted)return toast('无权删除此通知');activeId=id;modal('删除本人通知','<p>删除后普通浏览不可见，本人管理页保留记录。</p>',btn('确认删除','notice-delete-confirm','danger'))},
 'notice-delete-confirm':()=>{const n=S.notices.find(n=>n.id===activeId);if(n?.authorId!==authorId())return toast('没有此通知权限');n.deleted=true;log('删除通知',n.title);close();shell()},
 'user-new':()=>{userNew();$('#user-firm').innerHTML=options(scopeOptions(),'A',false)},'user-edit':editUser,'user-edit-save':saveUserEdit,'user-save':userSave,'user-role':openUserRoles,'user-role-save':userRolesSave,
 'user-toggle':id=>{const u=S.users.find(u=>u.id===id);if(lastManager(u))return toast('最后一个管理账号不能停用');originalActions['user-toggle'](id)},
 'user-delete':id=>{const u=S.users.find(u=>u.id===id);if(lastManager(u))return toast('最后一个管理账号不能删除');const reports=[...S.historyReports,...Object.values(S.reports).filter(Boolean)];if(reports.some(r=>r.submissionVersion&&(r.submittedBy===id||r.snapshots.some(v=>v.submittedBy===id))))return modal('有本人提交数据，禁止删除','<p>请使用停用，保留原始数据关联。</p>');activeId=id;modal('逻辑删除账号',`<p>确认删除 ${esc(u.login)}？</p>`,btn('确认删除账号','user-delete-confirm','danger'))},
 'role-new':()=>editRole(''),'role-edit':editRole,'role-save':saveRole,
 'role-delete':id=>{activeId=id;const r=S.roleTemplates.find(r=>r.id===id),n=S.users.filter(u=>u.roles.includes(r.name)).length;modal('删除角色并解除关联',`<p>${esc(r.name)} · 影响 ${n} 名用户。删除关联，保留用户与历史；无角色用户停止业务。</p>`,btn('确认删除模板','role-delete-confirm','danger'))},
 'role-delete-confirm':()=>{const r=S.roleTemplates.find(r=>r.id===activeId);S.users.forEach(u=>u.roles=u.roles.filter(v=>v!==r.name));S.roleTemplates=S.roleTemplates.filter(v=>v.id!==activeId);log('删除角色',r.name);close();shell()},
 'period-new':periodNew,'period-edit':month=>{periodEditing=month;dirty=false;shell()},
 'period-create':()=>{const month=$('#new-period').value,start=$('#new-start').value,end=$('#new-end').value;if(!month||!start||!end||start>=end||S.periods.some(p=>p.month===month))return errorMessages(['年月须唯一，开始时间必须早于截止。']);S.periods.push({month,start,end});periodEditing=month;log('新增调查期',month);close();shell()},
 'period-save':()=>{const p=S.periods.find(p=>p.month===periodEditing),start=$('#periodStart').value,end=$('#periodEnd').value;if(!start||!end||start>=end)return errorMessages(['开始必须早于截止。']);Object.assign(p,{start,end});if(p.month==='2026-09'){S.periodStart=start;S.periodEnd=end;S.open=S.now.replace(' ','T')>=start&&S.now.replace(' ','T')<end}dirty=false;log('修改调查期',p.month);shell();toast('调查窗口已更新，已提交快照保持不变')},
 'code-correct':codeCorrect,'code-save':codeSave,
 'dict-import-check':()=>{try{const a=JSON.parse($('#dict-json').value),codes=new Set(a.map(x=>x.code));if(!Array.isArray(a)||a.some(x=>!x.code||!x.name||!Number.isInteger(x.level)||x.level<1||x.level>3||typeof x.enabled!=='boolean')||codes.size!==a.length||a.some(x=>x.level===1?x.parentCode!==null:!a.some(p=>p.code===x.parentCode&&p.level===x.level-1)))throw Error();modal('地区配置校验通过',`<p>共 ${a.length} 项；代码唯一、层级及父子关系合法。该入口用于核对配置结构，本原型的地区演示仍使用固定两市两县。</p><pre class="pre">${esc(JSON.stringify(a,null,2))}</pre>`)}catch{errorMessages(['JSON须为完整地区数组，代码唯一，父级存在且层级连续，enabled为布尔值。'])}},
 boundaries:()=>modal('演示范围',`<p>本原型按SRS V1.1演示表单、审核、修订、13条件查询、备案取样饼图、两期多维与连续期分析、通知可见性、用户角色管理、调查期增改和模拟交换。</p><p>数据仅在浏览器内存中，刷新重置；方向记录可本地保存。角色切换用于评审，生产登录、服务端权限、数据库、真实监控、XLSX生成与国家接入由正式实现完成。地区JSON用于校验预览，分析最多连续24个月，示例仅有2026年6月、8月、9月。</p>`)
});
document.addEventListener('change',e=>{
 const t=e.target;
 if(t.id==='province-account'){S.provinceAccount=t.value;noticeMode='read';shell()}
 if(['q-city','ar-city','s-city'].includes(t.id)){const prefix=t.id.slice(0,-4);$('#'+prefix+'county').innerHTML=options(cityChoices.filter(c=>!t.value||c[0]===t.value).map(c=>[c[0]+'-K01',countyName(c[0]+'-K01')]),'')}
});
let historyFilters={name:'',month:'',state:''},reviewFilters={name:'',month:''};
historyPage=function(){const f=historyFilters,rows=allReports().filter(r=>r.submissionVersion&&(S.role==='enterprise'?r.id==='A':S.role==='city'?r.profile.cityCode==='YN-C01':true)&&(!f.name||r.profile.name.includes(f.name))&&(!f.month||r.period===f.month)&&(!f.state||r.status===f.state));return header('history')+`<section class="card"><div class="form-grid">${field('企业名称','h-name',f.name)}${field('调查月份','h-month',f.month,'month')}${selectField('数据状态','h-state',['CITY_PENDING','CITY_RETURNED','PROVINCE_PENDING','PROVINCE_RETURNED','APPROVED'].map(s=>[s,statuses[s][0]]),f.state)}</div><div class="form-actions">${btn('查询历史','history-search','primary')}${btn('清除','history-clear')}</div></section><section class="card"><h2>已提交报表 · ${rows.length} 条</h2>${rows.length?table(['企业','所属市','月份','B / E','状态','提交版本','操作'],rows.map(r=>tr([esc(r.profile.name),cityName(r.profile.cityCode),r.period,r.B+' / '+r.E,badge(r.status),'v'+r.submissionVersion,btn('查看详情','query-detail','small',false,r.id+'|'+r.period)]))):empty('暂无匹配历史','未正式提交的草稿不进入历史。')}</section>`};
const baseReviewPage=reviewPage;
reviewPage=function(){const f=reviewFilters,oldScoped=scopedReports;scopedReports=()=>oldScoped().filter(r=>(!f.name||r.profile.name.includes(f.name))&&(!f.month||r.period===f.month));let html;try{html=baseReviewPage()}finally{scopedReports=oldScoped}const filter=`<section class="card"><div class="form-grid">${field('企业名称','r-name',f.name)}${field('调查月份','r-month',f.month,'month')}</div><div class="form-actions">${btn('筛选待审','review-search','primary')}${btn('清除','review-clear')}</div></section>`;return html.replace('<div class="card"><h2>待审',filter+'<div class="card"><h2>待审')};
Object.assign(actionHandlers,{'history-search':()=>{historyFilters=readFilter('h-',['name','month','state']);shell()},'history-clear':()=>{historyFilters={name:'',month:'',state:''};shell()},'review-search':()=>{reviewFilters=readFilter('r-',['name','month']);shell()},'review-clear':()=>{reviewFilters={name:'',month:''};shell()}});
seed('daily');shell();
